export const ALERT_CLASSIFICATIONS = ["EVENT", "WARNING", "ALERT", "PAGE"] as const;
export const ALERT_SEVERITIES = ["LOW", "MEDIUM", "HIGH", "CRITICAL"] as const;
export const ALERT_THRESHOLD_SOURCES = [
  "DETERMINISTIC",
  "P15_EVIDENCE_REQUIRED",
  "BUSINESS_DECISION_REQUIRED",
  "SECURITY_POLICY_REQUIRED",
  "PROVIDER_EVIDENCE_REQUIRED",
  "COMPANY_STANDARD_REQUIRED",
] as const;
export const ALERT_FEATURE_DEPENDENCIES = ["ALWAYS", "AI_ENABLED", "TELEGRAM_ENABLED"] as const;
export const ALERT_GROUPING_DIMENSIONS = ["environment", "service", "component", "workload", "operation", "failure_category"] as const;

export type AlertClassification = (typeof ALERT_CLASSIFICATIONS)[number];
export type AlertSeverity = (typeof ALERT_SEVERITIES)[number];
export type AlertThresholdSource = (typeof ALERT_THRESHOLD_SOURCES)[number];
export type AlertFeatureDependency = (typeof ALERT_FEATURE_DEPENDENCIES)[number];

export type AlertSpecification = Readonly<{
  key: string;
  component: string;
  category: string;
  description: string;
  signal: string;
  condition: string;
  classification: AlertClassification;
  severity: AlertSeverity;
  thresholdSource: AlertThresholdSource;
  firing: string;
  recovery: string;
  missingData: string;
  sustained: "REQUIRED" | "NOT_REQUIRED" | "EXTERNAL_TARGET_REQUIRED";
  grouping: readonly (typeof ALERT_GROUPING_DIMENSIONS)[number][];
  suppression: string;
  owner: string;
  escalationOwner: string;
  runbook: string;
  privacy: "OPERATIONAL_MINIMIZED";
  feature: AlertFeatureDependency;
  futureDependency: string;
}>;

const common = {
  grouping: ["environment", "service", "component"] as const,
  suppression: "Suppress only for an approved maintenance or deployment window; emit recovery after the condition clears.",
  privacy: "OPERATIONAL_MINIMIZED" as const,
};

export const ALERT_SPECIFICATIONS: readonly AlertSpecification[] = [
  {key:"API_TARGET_UNAVAILABLE",component:"API",category:"AVAILABILITY",description:"The API target is absent or the process is unavailable.",signal:"External target presence plus API liveness",condition:"Target absence is evaluated by the future collector; the application cannot observe its own complete absence.",classification:"PAGE",severity:"HIGH",thresholdSource:"COMPANY_STANDARD_REQUIRED",firing:"External target is absent for the company-approved sustained interval.",recovery:"Target is present and liveness succeeds through the recovery hold.",missingData:"No target samples are not healthy; distinguish collector failure from target absence.",sustained:"EXTERNAL_TARGET_REQUIRED",...common,owner:"SRE",escalationOwner:"Backend",runbook:"p11-runbooks.md#api-availability-and-readiness",feature:"ALWAYS",futureDependency:"P13 collector and company outage policy"},
  {key:"API_REQUIRED_READINESS_FAILURE",component:"API",category:"READINESS",description:"One or more required API readiness components are not ready.",signal:"aims_readiness_status and readiness_failed",condition:"A required component reports not-ready; disabled optional features are excluded.",classification:"ALERT",severity:"HIGH",thresholdSource:"DETERMINISTIC",firing:"Required readiness remains failed through anti-flap evaluation.",recovery:"Every required component reports ready through the recovery hold.",missingData:"Missing readiness samples require external target evaluation and are not interpreted as ready.",sustained:"REQUIRED",...common,owner:"SRE",escalationOwner:"Backend",runbook:"p11-runbooks.md#api-availability-and-readiness",feature:"ALWAYS",futureDependency:"P13 evaluator duration"},
  {key:"API_5XX_RATE_DEGRADATION",component:"API",category:"PERFORMANCE",description:"The bounded API 5xx rate is abnormally elevated.",signal:"aims_http_requests_total",condition:"Rate over an approved window exceeds the evidence-backed threshold.",classification:"WARNING",severity:"MEDIUM",thresholdSource:"P15_EVIDENCE_REQUIRED",firing:"Configured rate/window condition is sustained.",recovery:"Rate returns below the approved recovery threshold.",missingData:"No samples require target-health evaluation; zero completed failures is distinct from no samples.",sustained:"REQUIRED",...common,owner:"Backend",escalationOwner:"SRE",runbook:"p11-runbooks.md#api-availability-and-readiness",feature:"ALWAYS",futureDependency:"P15 load evidence and P13 evaluator"},
  {key:"API_LATENCY_DEGRADATION",component:"API",category:"PERFORMANCE",description:"API latency is abnormally degraded.",signal:"aims_http_request_duration_seconds",condition:"Approved route-class latency objective is breached over an evidence-backed window.",classification:"WARNING",severity:"MEDIUM",thresholdSource:"P15_EVIDENCE_REQUIRED",firing:"Latency breach is sustained.",recovery:"Latency returns below the approved recovery objective.",missingData:"No samples require target-health evaluation.",sustained:"REQUIRED",...common,owner:"Backend",escalationOwner:"SRE",runbook:"p11-runbooks.md#api-availability-and-readiness",feature:"ALWAYS",futureDependency:"P15 load/soak evidence"},
  {key:"SCHEMA_VERSION_MISMATCH",component:"DATABASE",category:"CONFIGURATION",description:"Runtime schema readiness is not exactly the expected version.",signal:"aims_readiness_status component schema",condition:"Schema readiness reports not-ready for expected schema 58.",classification:"ALERT",severity:"HIGH",thresholdSource:"DETERMINISTIC",firing:"Schema mismatch is observed.",recovery:"Readiness observes schema 58.",missingData:"Missing samples defer to target/readiness monitoring; never run migrations automatically.",sustained:"NOT_REQUIRED",...common,owner:"DBA",escalationOwner:"SRE",runbook:"p11-runbooks.md#schema-mismatch",feature:"ALWAYS",futureDependency:"P13 deployment correlation"},
  {key:"DATABASE_UNAVAILABLE",component:"DATABASE",category:"DATABASE",description:"Required PostgreSQL connectivity is unavailable.",signal:"readiness plus aims_db_operations_total",condition:"Database readiness fails or bounded connection failures prove unavailability.",classification:"PAGE",severity:"CRITICAL",thresholdSource:"BUSINESS_DECISION_REQUIRED",firing:"Unavailability persists for the approved outage interval.",recovery:"Connectivity, readiness and required executor checks succeed.",missingData:"Missing application samples require external target and managed-service health checks.",sustained:"REQUIRED",...common,owner:"DBA",escalationOwner:"SRE",runbook:"p11-runbooks.md#database-unavailable-or-degraded",feature:"ALWAYS",futureDependency:"Company outage tolerance and P13 platform health"},
  {key:"DATABASE_POOL_DEGRADATION",component:"DATABASE",category:"DATABASE",description:"Database pool waiting indicates capacity pressure.",signal:"aims_db_pool_connections",condition:"Waiting/total behavior breaches an evidence-backed threshold.",classification:"WARNING",severity:"MEDIUM",thresholdSource:"P15_EVIDENCE_REQUIRED",firing:"Pressure is sustained.",recovery:"Pool waiting returns below the approved recovery threshold.",missingData:"No pool samples require application target evaluation.",sustained:"REQUIRED",...common,owner:"DBA",escalationOwner:"Backend",runbook:"p11-runbooks.md#database-unavailable-or-degraded",feature:"ALWAYS",futureDependency:"P15 capacity evidence"},
  {key:"DATABASE_TIMEOUT_LOCK_DEGRADATION",component:"DATABASE",category:"DATABASE",description:"Timeout or lock-related database failures are elevated.",signal:"aims_db_operations_total and aims_db_operation_duration_seconds",condition:"Bounded timeout/lock outcomes exceed the evidence-backed pattern threshold.",classification:"ALERT",severity:"HIGH",thresholdSource:"P15_EVIDENCE_REQUIRED",firing:"Failure pattern is sustained.",recovery:"Failure and duration behavior returns to the approved range.",missingData:"No samples require target-health evaluation.",sustained:"REQUIRED",...common,owner:"DBA",escalationOwner:"Backend",runbook:"p11-runbooks.md#database-unavailable-or-degraded",feature:"ALWAYS",futureDependency:"P15 concurrency/soak evidence"},
  {key:"TRUSTED_EXECUTOR_FAILURE",component:"DATABASE",category:"DATABASE",description:"A required trusted Finance or Payment executor cannot perform its bounded operation.",signal:"readiness and aims_db_operations_total EXECUTOR_CALL",condition:"Required executor readiness fails or technical executor calls repeatedly fail.",classification:"ALERT",severity:"HIGH",thresholdSource:"DETERMINISTIC",firing:"Executor capability is unavailable; business denials are excluded.",recovery:"Executor readiness and a bounded technical operation succeed.",missingData:"Missing samples require target-health evaluation.",sustained:"REQUIRED",...common,owner:"DBA",escalationOwner:"Backend",runbook:"p11-runbooks.md#database-unavailable-or-degraded",feature:"ALWAYS",futureDependency:"P13 evaluator"},
  {key:"WORKER_TARGET_UNAVAILABLE",component:"WORKER",category:"WORKER",description:"The required document worker target is absent or not ready.",signal:"aims_worker_up, worker readiness and external target presence",condition:"Target absence or not-ready state occurs while the document workload is required.",classification:"ALERT",severity:"HIGH",thresholdSource:"COMPANY_STANDARD_REQUIRED",firing:"Absence/not-ready is sustained and backlog may exist; idle with zero backlog is not an incident.",recovery:"Worker target is present, ready and capable.",missingData:"No samples require external target evaluation.",sustained:"EXTERNAL_TARGET_REQUIRED",...common,owner:"SRE",escalationOwner:"Backend",runbook:"p11-runbooks.md#worker-unavailable-and-backlog",feature:"ALWAYS",futureDependency:"P13 supervision/collector"},
  {key:"WORKER_BACKLOG_AGE_GROWTH",component:"WORKER",category:"WORKER",description:"Work is aging or growing abnormally.",signal:"aims_worker_backlog and aims_worker_oldest_pending_seconds",condition:"Oldest age or growth breaches evidence-backed workload thresholds.",classification:"WARNING",severity:"MEDIUM",thresholdSource:"P15_EVIDENCE_REQUIRED",firing:"Age/growth condition is sustained.",recovery:"Age and growth return below approved recovery values.",missingData:"Zero backlog is healthy only when a current sample exists.",sustained:"REQUIRED",...common,owner:"Backend",escalationOwner:"SRE",runbook:"p11-runbooks.md#worker-unavailable-and-backlog",feature:"ALWAYS",futureDependency:"P15 throughput/provider evidence"},
  {key:"WORKER_TERMINAL_BACKLOG",component:"WORKER",category:"WORKER",description:"Terminal work exists and requires operator investigation.",signal:"aims_worker_backlog state TERMINAL",condition:"Terminal backlog is present under the approved workload policy.",classification:"ALERT",severity:"HIGH",thresholdSource:"BUSINESS_DECISION_REQUIRED",firing:"Terminal backlog meets the approved actionable condition.",recovery:"Terminal items are safely reconciled and current terminal backlog clears.",missingData:"No sample is unknown, not zero.",sustained:"NOT_REQUIRED",...common,owner:"Backend",escalationOwner:"SRE",runbook:"p11-runbooks.md#worker-unavailable-and-backlog",feature:"ALWAYS",futureDependency:"Finance/Security terminal-work policy"},
  {key:"WORKER_LEASE_RECOVERY_RATE",component:"WORKER",category:"WORKER",description:"Authoritative expired-lease recoveries are abnormally frequent.",signal:"aims_worker_lease_recoveries_total",condition:"Recovery rate exceeds an evidence-backed workload threshold.",classification:"WARNING",severity:"MEDIUM",thresholdSource:"P15_EVIDENCE_REQUIRED",firing:"Abnormal rate is sustained; one recovery is an event.",recovery:"Recovery rate returns to baseline.",missingData:"No sample is evaluated with worker target health.",sustained:"REQUIRED",...common,owner:"Backend",escalationOwner:"SRE",runbook:"p11-runbooks.md#worker-unavailable-and-backlog",feature:"ALWAYS",futureDependency:"P15 soak evidence"},
  {key:"DOCUMENT_TERMINAL_FAILURE_BACKLOG",component:"DOCUMENT_SCAN",category:"DOCUMENT_SECURITY",description:"Document processing has terminal infrastructure failures requiring investigation.",signal:"worker terminal backlog and terminal failure outcomes",condition:"Terminal scan-processing backlog meets approved policy; normal REJECTED verdicts are excluded.",classification:"ALERT",severity:"HIGH",thresholdSource:"BUSINESS_DECISION_REQUIRED",firing:"Actionable terminal backlog exists.",recovery:"Terminal processing failures are reconciled and the queue is healthy.",missingData:"No worker samples require target evaluation.",sustained:"NOT_REQUIRED",...common,owner:"Security",escalationOwner:"Backend",runbook:"p11-runbooks.md#document-terminal-processing-and-scanner-storage",feature:"ALWAYS",futureDependency:"Security/Finance evidence-handling policy"},
  {key:"SCANNER_STORAGE_UNAVAILABLE",component:"DOCUMENT_SCAN",category:"DOCUMENT_SECURITY",description:"Required scanner or document storage infrastructure is unavailable.",signal:"readiness and bounded STORAGE/SCANNER worker failures",condition:"Required dependency readiness fails or technical failures are sustained.",classification:"ALERT",severity:"HIGH",thresholdSource:"DETERMINISTIC",firing:"Required dependency is unavailable; document REJECTED is excluded.",recovery:"Storage/scanner readiness and processing succeed.",missingData:"Missing samples require worker target evaluation.",sustained:"REQUIRED",...common,owner:"Security",escalationOwner:"SRE",runbook:"p11-runbooks.md#document-terminal-processing-and-scanner-storage",feature:"ALWAYS",futureDependency:"P3/P4 provider and P13 deployment"},
  {key:"TELEGRAM_DELIVERY_DEGRADATION",component:"TELEGRAM",category:"TELEGRAM",description:"Enabled Telegram delivery has backlog, terminal, rate-limit or provider degradation.",signal:"Telegram worker backlog/age and provider outcomes",condition:"Only active when Telegram is enabled and the provider-evidence threshold is breached.",classification:"WARNING",severity:"MEDIUM",thresholdSource:"PROVIDER_EVIDENCE_REQUIRED",firing:"Enabled delivery degradation is sustained.",recovery:"Delivery success and backlog return to approved values.",missingData:"When disabled, missing Telegram metrics are healthy; when enabled, evaluate target/provider health.",sustained:"REQUIRED",...common,owner:"Telegram Integration Owner",escalationOwner:"SRE",runbook:"p11-runbooks.md#optional-telegram-and-ai-provider-degradation",feature:"TELEGRAM_ENABLED",futureDependency:"Telegram approval and provider evidence"},
  {key:"AI_PROVIDER_DEGRADATION",component:"AI",category:"AI_PROVIDER",description:"Enabled advisory AI provider operations are degraded.",signal:"aims_provider_operations_total and duration for AI",condition:"Only active when AI is enabled and provider errors/timeouts/schema failures breach evidence.",classification:"WARNING",severity:"LOW",thresholdSource:"PROVIDER_EVIDENCE_REQUIRED",firing:"Enabled provider degradation is sustained.",recovery:"Provider success and response behavior recover.",missingData:"When AI is OFF, missing AI metrics are healthy; when enabled, evaluate provider health.",sustained:"REQUIRED",...common,owner:"AI Integration Owner",escalationOwner:"Backend",runbook:"p11-runbooks.md#optional-telegram-and-ai-provider-degradation",feature:"AI_ENABLED",futureDependency:"AI provider approval and evidence"},
  {key:"AUTH_SECURITY_FAILURE_PATTERN",component:"AUTH",category:"AUTHENTICATION_SECURITY",description:"Authentication, CSRF/origin, webhook/action or forbidden-authority failures form a security-relevant pattern.",signal:"bounded aims_domain_operations_total outcomes",condition:"A bounded category rate/pattern exceeds approved Security policy; isolated user mistakes are events.",classification:"ALERT",severity:"HIGH",thresholdSource:"SECURITY_POLICY_REQUIRED",firing:"Security-approved pattern condition is met.",recovery:"Pattern ceases and Security confirms containment/recovery.",missingData:"No samples require API target evaluation.",sustained:"REQUIRED",...common,owner:"Security",escalationOwner:"SRE",runbook:"p11-runbooks.md#authentication-and-security-patterns",feature:"ALWAYS",futureDependency:"Company Security policy"},
  {key:"FINANCE_CONTROL_INFRASTRUCTURE_FAILURE",component:"FINANCE_CONTROL",category:"FINANCE_CONTROL",description:"Finance Control cannot execute because of technical infrastructure failure.",signal:"domain and trusted-executor DB outcomes",condition:"Technical execution fails; deterministic Finance Control FAIL/HOLD is excluded.",classification:"ALERT",severity:"HIGH",thresholdSource:"DETERMINISTIC",firing:"Trusted execution is unavailable or repeatedly technically fails.",recovery:"A current authorized technical execution path succeeds.",missingData:"No samples require API/DB target evaluation.",sustained:"REQUIRED",...common,owner:"Backend",escalationOwner:"Finance Operations",runbook:"p11-runbooks.md#finance-control-infrastructure-failure",feature:"ALWAYS",futureDependency:"P13 evaluator"},
  {key:"PAYMENT_INFRASTRUCTURE_FAILURE",component:"PAYMENT",category:"PAYMENT",description:"Payment recording cannot complete because of DB, executor or rollback failure.",signal:"Payment domain outcomes and trusted-executor DB outcomes",condition:"Technical Payment failure occurs; SUCCESS and IDEMPOTENT_REPLAY are excluded.",classification:"PAGE",severity:"CRITICAL",thresholdSource:"BUSINESS_DECISION_REQUIRED",firing:"Approved integrity/availability impact condition is met.",recovery:"Payment path is healthy and Finance reconciliation confirms consistent state.",missingData:"No samples require API/DB target evaluation.",sustained:"REQUIRED",...common,owner:"Backend",escalationOwner:"Finance Operations",runbook:"p11-runbooks.md#payment-infrastructure-and-integrity",feature:"ALWAYS",futureDependency:"Finance outage policy and P13 evaluator"},
  {key:"PAYMENT_PAYLOAD_MISMATCH_PATTERN",component:"PAYMENT",category:"PAYMENT_SECURITY",description:"Payment payload mismatches form a security or integration pattern.",signal:"aims_domain_operations_total PAYMENT_RECORD PAYLOAD_MISMATCH",condition:"Security-approved rate/pattern is met; one mismatch is not an automatic page.",classification:"ALERT",severity:"HIGH",thresholdSource:"SECURITY_POLICY_REQUIRED",firing:"Approved bounded mismatch pattern occurs.",recovery:"Pattern stops and Security/Backend confirms the source is contained.",missingData:"No samples require API target evaluation.",sustained:"REQUIRED",...common,owner:"Security",escalationOwner:"Backend",runbook:"p11-runbooks.md#payment-infrastructure-and-integrity",feature:"ALWAYS",futureDependency:"Company Security policy"},
  {key:"PAYMENT_IDEMPOTENT_REPLAY_RATE",component:"PAYMENT",category:"RELIABILITY",description:"Valid idempotent replay is abnormally frequent.",signal:"aims_domain_operations_total PAYMENT_RECORD IDEMPOTENT_REPLAY",condition:"Evidence-backed replay rate is abnormal; each replay remains a successful recovery event.",classification:"WARNING",severity:"LOW",thresholdSource:"P15_EVIDENCE_REQUIRED",firing:"Abnormal rate is sustained.",recovery:"Replay rate returns to normal.",missingData:"No samples require API target evaluation.",sustained:"REQUIRED",...common,owner:"Backend",escalationOwner:"SRE",runbook:"p11-runbooks.md#payment-infrastructure-and-integrity",feature:"ALWAYS",futureDependency:"P15 reliability evidence"},
] as const;

export type AlertFeatureState = Readonly<{aiEnabled:boolean;telegramEnabled:boolean}>;
export function isAlertSpecificationActive(specification: AlertSpecification, features: AlertFeatureState) {
  if (specification.feature === "AI_ENABLED") return features.aiEnabled;
  if (specification.feature === "TELEGRAM_ENABLED") return features.telegramEnabled;
  return true;
}

export const NORMAL_BUSINESS_OUTCOMES = [
  "APPROVAL_REJECTION", "APPROVAL_CLARIFICATION", "FINANCE_CONTROL_FAIL",
  "DOCUMENT_REJECTED", "PAYMENT_SUCCESS", "PAYMENT_IDEMPOTENT_REPLAY",
  "POLICY_DENIAL", "LEGITIMATE_AUTHORIZATION_DENIAL", "AI_MANUAL_FALLBACK",
] as const;

export function isInfrastructureIncidentOutcome(value:string){
  return !NORMAL_BUSINESS_OUTCOMES.includes(value as (typeof NORMAL_BUSINESS_OUTCOMES)[number]);
}
