export const FINANCE_CONTROL_CHECK_CODES = [
  "REQUEST_NOT_APPROVED",
  "REQUEST_REVISION_CHANGED",
  "APPROVAL_NOT_CURRENT",
  "APPROVAL_ROUTE_INCOMPLETE",
  "APPROVER_AUTHORITY_INVALID",
  "EVIDENCE_MISMATCH",
  "REQUIRED_EVIDENCE_MISSING",
  "AMOUNT_CHANGED",
  "PAYEE_CHANGED",
  "CURRENCY_CHANGED",
  "DEPARTMENT_OR_CATEGORY_CHANGED",
  "PAYMENT_DETAILS_CHANGED",
  "VALIDATION_STALE",
  "FINANCE_CONTEXT_STALE",
  "FINANCIAL_ANALYSIS_STALE",
  "POLICY_DECISION_STALE",
  "COMMITMENT_MISSING",
  "COMMITMENT_NOT_ACTIVE",
  "COMMITMENT_AMOUNT_MISMATCH",
  "COMMITMENT_CURRENCY_MISMATCH",
  "COMMITMENT_BUDGET_INVALID",
  "DUPLICATE_INVOICE",
  "DUPLICATE_PAYMENT",
  "PAYMENT_DETAILS_INCOMPLETE",
  "PAYEE_VERIFIED",
  "PAYMENT_METHOD_VERIFIED",
  "PAYMENT_DETAILS_VERIFIED",
  "SUPPORTING_DOCUMENTS_VERIFIED",
  "POSSIBLE_DUPLICATE_REVIEWED",
] as const;

export type FinanceControlCheckCode =
  (typeof FINANCE_CONTROL_CHECK_CODES)[number];

export type DuplicateStatus =
  | "NO_DUPLICATE"
  | "POSSIBLE_DUPLICATE"
  | "CONFIRMED_DUPLICATE";

export function classifyDuplicate(
  exactDocumentMatch: boolean,
  matchingBusinessFields: boolean,
): DuplicateStatus {
  if (exactDocumentMatch) return "CONFIRMED_DUPLICATE";
  if (matchingBusinessFields) return "POSSIBLE_DUPLICATE";
  return "NO_DUPLICATE";
}
