import type {Pool,PoolClient} from "pg";
import type {DocumentStorage,StorageObjectPage} from "../storage/document-storage.js";
import {SUPPORTED_MIGRATION_ID,SUPPORTED_SCHEMA_VERSION,type RecoveryManifest} from "./recovery-manifest.js";

export type RecoveryCheckStatus="PASS"|"WARNING"|"FAIL"|"MANUAL_RECONCILIATION_REQUIRED"|"NOT_VERIFIABLE"|"NOT_APPLICABLE";
export interface RecoveryFinding{code:string;status:Exclude<RecoveryCheckStatus,"PASS">;count:number;reference?:string}
export interface RecoveryCheck{name:string;status:RecoveryCheckStatus;count:number}
export interface VerificationCoverage{mode:"FULL"|"LIMITED";eligible:number;processed:number;failed:number;unverified:number;complete:boolean}
export interface RestoreVerificationResult{verificationVersion:"1";environment:RecoveryManifest["environment"];manifestReference:string;schema:{version:number;migrationId:string};recoveryGeneration:{status:"GENERATION_READY"|"GENERATION_ADVANCE_REQUIRED"|"GENERATION_STATE_INVALID";generation?:string;sequence?:number};documentCoverage:VerificationCoverage;orphanCoverage:{processed:number;orphans:number;complete:boolean};overallStatus:"PASS"|"WARNING"|"FAIL"|"MANUAL_RECONCILIATION_REQUIRED";checks:RecoveryCheck[];findings:RecoveryFinding[];aggregateFindingCount:number;truncated:boolean;manualReconciliationRequirements:string[];resumeRecommendation:"VALIDATION_PASSED_HUMAN_APPROVAL_REQUIRED"|"NOT_SAFE_TO_RESUME"}
export interface RestoreCheckerOptions{pool:Pool;storage?:DocumentStorage;manifest:RecoveryManifest;runningApplicationRelease:string;manifestReference:string;maxDetailedFindings?:number;documentTimeoutMs?:number;overallTimeoutMs?:number;documentPageSize?:number;objectPageSize?:number;documentMode?:"FULL"|"LIMITED";maxDocuments?:number;signal?:AbortSignal}
type Add=(name:string,code:string,status:RecoveryCheckStatus,count?:number,reference?:string)=>void;type CountRow={count:string};
const n=(value:string|number):number=>Number(value),MAX_PAGES=10_000,MAX_CURSOR_LENGTH=1024;
class VerificationDeadlineError extends Error{constructor(){super("VERIFICATION_DEADLINE_EXCEEDED")}}
class StorageOperationTimeoutError extends Error{constructor(){super("STORAGE_OPERATION_TIMEOUT")}}
class StorageOperationCleanupTimeoutError extends Error{constructor(){super("STORAGE_OPERATION_CLEANUP_TIMEOUT")}}

export async function runRestoreChecker(options:RestoreCheckerOptions):Promise<RestoreVerificationResult>{
 const max=Math.min(Math.max(options.maxDetailedFindings??100,1),500),overallTimeoutMs=integer(options.overallTimeoutMs??60_000,100,600_000,"overallTimeoutMs"),objectTimeoutMs=integer(options.documentTimeoutMs??3_000,100,30_000,"documentTimeoutMs"),documentPageSize=integer(options.documentPageSize??200,1,500,"documentPageSize"),objectPageSize=integer(options.objectPageSize??200,1,500,"objectPageSize");
 const findings:RecoveryFinding[]=[],checks:RecoveryCheck[]=[];let aggregateFindingCount=0,savepointSequence=0;
 const documentCoverage:VerificationCoverage={mode:options.documentMode??"FULL",eligible:0,processed:0,failed:0,unverified:0,complete:false},orphanCoverage={processed:0,orphans:0,complete:false};
 const add:Add=(name,code,status,count=0,reference)=>{checks.push({name,status,count});if(status==="PASS"||status==="NOT_APPLICABLE")return;aggregateFindingCount+=Math.max(count,1);if(findings.length<max)findings.push({code,status:status as RecoveryFinding["status"],count,...(reference?{reference}:{})})};
 const deadline=Date.now()+overallTimeoutMs,controller=new AbortController(),timer=setTimeout(()=>controller.abort(),overallTimeoutMs);timer.unref?.();const abort=()=>controller.abort();options.signal?.addEventListener("abort",abort,{once:true});if(options.signal?.aborted){controller.abort();add("checker-execution","VERIFICATION_CANCELLED","FAIL",1)}
 const remaining=()=>{if(controller.signal.aborted||Date.now()>=deadline)throw new VerificationDeadlineError();return Math.max(1,deadline-Date.now())};
 let client:PoolClient|undefined,destroyClient=false;let schema={version:0,migrationId:"UNREADABLE"},recoveryGeneration:RestoreVerificationResult["recoveryGeneration"]={status:"GENERATION_STATE_INVALID"};
 const acquire=async():Promise<PoolClient>=>{const milliseconds=remaining();let expired=false;const pending=options.pool.connect().then(acquired=>{if(expired){acquired.release(true);throw new VerificationDeadlineError()}return acquired});try{return await deadlineBounded(pending,milliseconds,controller.signal)}catch(error){expired=true;throw error}};
 const execute=async<T>(operation:(active:PoolClient)=>Promise<T>,configureTimeout=true):Promise<T>=>{const active=client;if(!active)throw new VerificationDeadlineError();let milliseconds=remaining();const destroy=()=>{destroyClient=true;active.release(true);if(client===active)client=undefined};if(configureTimeout){await deadlineBounded(active.query(`SET LOCAL statement_timeout=${milliseconds}`),milliseconds,controller.signal,destroy);milliseconds=remaining()}const value=await deadlineBounded(operation(active),milliseconds,controller.signal,destroy);remaining();return value};
 const isolated=async<T>(operation:()=>Promise<T>):Promise<T>=>{const name=`p12_check_${++savepointSequence}`;await execute(active=>active.query(`SAVEPOINT ${name}`));try{const value=await execute(()=>operation());await execute(active=>active.query(`RELEASE SAVEPOINT ${name}`));return value}catch(error){if(error instanceof VerificationDeadlineError||controller.signal.aborted)throw new VerificationDeadlineError();await execute(active=>active.query(`ROLLBACK TO SAVEPOINT ${name}`));await execute(active=>active.query(`RELEASE SAVEPOINT ${name}`));throw error}};
 try{
  client=await acquire();await execute(active=>active.query("BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ READ ONLY;SET LOCAL ROLE aims_owner"),false);const connected=client;if(!connected)throw new VerificationDeadlineError();
  try{const version=await isolated(()=>connected.query<{version:number;migration_id:string}>("SELECT version,migration_id FROM aims_schema_version WHERE singleton"));if(version.rowCount!==1)add("schema","SCHEMA_SINGLETON_INVALID","FAIL",version.rowCount??0);else{schema={version:version.rows[0].version,migrationId:version.rows[0].migration_id};add("schema","SCHEMA_UNSUPPORTED",schema.version===SUPPORTED_SCHEMA_VERSION&&schema.migrationId===SUPPORTED_MIGRATION_ID?"PASS":"FAIL",schema.version===SUPPORTED_SCHEMA_VERSION?0:1)}}catch(error){if(error instanceof VerificationDeadlineError)throw error;add("schema","SCHEMA_CHECK_FAILED","FAIL",1)}
  add("application-release","APPLICATION_RELEASE_MISMATCH",options.manifest.applicationRelease===options.runningApplicationRelease?"PASS":"FAIL",options.manifest.applicationRelease===options.runningApplicationRelease?0:1);add("manifest-schema-binding","MANIFEST_SCHEMA_MISMATCH",options.manifest.schemaVersion===schema.version&&options.manifest.latestMigrationId===schema.migrationId?"PASS":"FAIL",options.manifest.schemaVersion===schema.version?0:1);
  try{const generation=await isolated(()=>connected.query<{generation:string;generation_sequence:string;event_count:string;max_sequence:string;exact_event:boolean;current_event_count:string}>(`SELECT g.generation::text,g.generation_sequence::text,(SELECT count(*)::text FROM aims_recovery_generation_events)event_count,(SELECT COALESCE(max(generation_sequence),0)::text FROM aims_recovery_generation_events)max_sequence,(SELECT count(*)::text FROM aims_recovery_generation_events e WHERE e.generation_sequence=g.generation_sequence)current_event_count,EXISTS(SELECT 1 FROM aims_recovery_generation_events e WHERE e.generation_sequence=g.generation_sequence AND e.generation=g.generation AND e.correlation_id=g.correlation_id AND e.advanced_at=g.advanced_at AND e.reason=g.reason)exact_event FROM aims_recovery_generation g WHERE singleton`));const row=generation.rows[0],valid=generation.rowCount===1&&n(row?.event_count??0)===n(row?.generation_sequence??-1)&&n(row?.max_sequence??0)===n(row?.generation_sequence??-1)&&n(row?.current_event_count??0)===1&&row?.exact_event===true;if(!valid)add("recovery-generation","GENERATION_STATE_INVALID","FAIL",1);else{const ready=row.generation===options.manifest.expectedRecoveryGeneration;recoveryGeneration={status:ready?"GENERATION_READY":"GENERATION_ADVANCE_REQUIRED",generation:row.generation,sequence:n(row.generation_sequence)};add("recovery-generation",ready?"GENERATION_READY":"GENERATION_ADVANCE_REQUIRED",ready?"PASS":"FAIL",ready?0:1)}}catch(error){if(error instanceof VerificationDeadlineError)throw error;add("recovery-generation","GENERATION_STATE_INVALID","FAIL",1)}
  for(const item of financialChecks())await countCheck(connected,isolated,add,...item);await securityChecks(connected,isolated,add);await residualChecks(connected,isolated,add);await documentChecks(connected,isolated,options,add,documentCoverage,orphanCoverage,controller.signal,remaining,objectTimeoutMs,documentPageSize,objectPageSize);add("external-payment-reality","EXTERNAL_PAYMENT_RECONCILIATION_REQUIRED","MANUAL_RECONCILIATION_REQUIRED",1);await execute(active=>active.query("ROLLBACK"));
 }catch(error){if(client&&!destroyClient)await execute(active=>active.query("ROLLBACK")).catch(()=>{destroyClient=true;client?.release(true);client=undefined});add("checker-execution",error instanceof VerificationDeadlineError||controller.signal.aborted?"VERIFICATION_DEADLINE_EXCEEDED":"CHECK_EXECUTION_FAILED","FAIL",1)}finally{clearTimeout(timer);options.signal?.removeEventListener("abort",abort);if(client)client.release(destroyClient)}
 const hasFail=checks.some(check=>check.status==="FAIL"||check.status==="NOT_VERIFIABLE"),hasManual=checks.some(check=>check.status==="MANUAL_RECONCILIATION_REQUIRED"),hasWarning=checks.some(check=>check.status==="WARNING");
 return{verificationVersion:"1",environment:options.manifest.environment,manifestReference:options.manifestReference,schema,recoveryGeneration,documentCoverage,orphanCoverage,overallStatus:hasFail?"FAIL":hasManual?"MANUAL_RECONCILIATION_REQUIRED":hasWarning?"WARNING":"PASS",checks,findings,aggregateFindingCount,truncated:aggregateFindingCount>findings.length,manualReconciliationRequirements:hasManual?["EXTERNAL_PAYMENT_RECONCILIATION_REQUIRED","CURRENT_IDENTITY_AUTHORITY_RECONCILIATION_REQUIRED","HUMAN_RECOVERY_APPROVAL_REQUIRED"]:[],resumeRecommendation:hasFail?"NOT_SAFE_TO_RESUME":"VALIDATION_PASSED_HUMAN_APPROVAL_REQUIRED"};
}

function integer(value:number,min:number,max:number,name:string){if(!Number.isSafeInteger(value)||value<min||value>max)throw new Error(`Invalid bounded ${name}`);return value}
function financialChecks():[string,string,string][]{return[
 ["paid-payment","PAID_WITHOUT_EXACT_PAYMENT",`SELECT count(*)::text count FROM payment_requests r LEFT JOIN LATERAL(SELECT count(*) n FROM payments p WHERE p.payment_request_id=r.id)x ON true WHERE r.status='PAID' AND x.n<>1`],
 ["payment-request","PAYMENT_REQUEST_STATE_INVALID",`SELECT count(*)::text count FROM payments p LEFT JOIN payment_requests r ON r.id=p.payment_request_id WHERE r.id IS NULL OR r.status<>'PAID' OR p.ticket_number<>r.ticket_number OR p.payee<>r.payee OR p.department_id<>r.department_id OR p.category<>r.category OR p.purpose<>r.purpose OR p.amount_minor<>(r.amount*100)::bigint OR p.currency<>r.currency OR p.payment_method<>r.payment_method`],
 ["payment-ledger","PAYMENT_LEDGER_INCONSISTENT",`SELECT count(*)::text count FROM payments p LEFT JOIN financial_ledger_entries l ON l.id=p.ledger_entry_id LEFT JOIN budget_commitments c ON c.id=p.commitment_id WHERE l.id IS NULL OR l.reference_type<>'PAYMENT' OR l.reference_id IS DISTINCT FROM p.id OR l.entry_type<>'ACTUAL' OR l.amount_minor<>p.amount_minor OR l.currency<>p.currency OR l.budget_id IS DISTINCT FROM c.budget_id`],
 ["reverse-payment-ledger","REVERSE_PAYMENT_LEDGER_INCONSISTENT",`SELECT count(*)::text count FROM financial_ledger_entries l LEFT JOIN payments p ON p.id=l.reference_id LEFT JOIN budget_commitments c ON c.id=p.commitment_id WHERE l.reference_type='PAYMENT' AND(p.id IS NULL OR p.ledger_entry_id IS DISTINCT FROM l.id OR l.entry_type<>'ACTUAL' OR l.amount_minor IS DISTINCT FROM p.amount_minor OR l.currency IS DISTINCT FROM p.currency OR l.budget_id IS DISTINCT FROM c.budget_id)`],
 ["payment-commitment","PAYMENT_COMMITMENT_INCONSISTENT",`SELECT count(*)::text count FROM payments p LEFT JOIN budget_commitments c ON c.id=p.commitment_id WHERE c.id IS NULL OR c.payment_request_id IS DISTINCT FROM p.payment_request_id OR c.approval_case_id IS DISTINCT FROM p.approval_case_id OR c.status<>'CONSUMED' OR c.source<>'APPROVAL' OR c.payment_id IS DISTINCT FROM p.id OR c.amount_minor<>p.amount_minor OR c.currency<>p.currency`],
 ["reverse-payment-commitment","REVERSE_PAYMENT_COMMITMENT_INCONSISTENT",`SELECT count(*)::text count FROM budget_commitments c LEFT JOIN payments p ON p.id=c.payment_id LEFT JOIN finance_control_runs f ON f.id=p.finance_control_run_id WHERE c.status='CONSUMED' AND(c.payment_id IS NULL OR p.id IS NULL OR p.commitment_id IS DISTINCT FROM c.id OR c.payment_request_id IS DISTINCT FROM p.payment_request_id OR c.approval_case_id IS DISTINCT FROM p.approval_case_id OR c.id IS DISTINCT FROM f.commitment_id OR c.amount_minor IS DISTINCT FROM p.amount_minor OR c.currency IS DISTINCT FROM p.currency)`],
 ["duplicate-ledger","DUPLICATE_LEDGER_EFFECT",`SELECT count(*)::text count FROM(SELECT p.id FROM payments p LEFT JOIN financial_ledger_entries l ON l.reference_type='PAYMENT' AND l.reference_id=p.id GROUP BY p.id HAVING count(l.id)<>1)x`],
 ["payment-lineage","PAYMENT_LINEAGE_INVALID",`SELECT count(*)::text count FROM payments p LEFT JOIN payment_requests r ON r.id=p.payment_request_id LEFT JOIN approval_cases a ON a.id=p.approval_case_id LEFT JOIN finance_control_runs f ON f.id=p.finance_control_run_id LEFT JOIN budget_commitments c ON c.id=p.commitment_id WHERE a.id IS NULL OR a.payment_request_id IS DISTINCT FROM p.payment_request_id OR a.status<>'APPROVED' OR NOT a.is_current OR f.id IS NULL OR f.payment_request_id IS DISTINCT FROM p.payment_request_id OR f.status<>'PASSED' OR NOT f.is_current OR f.approval_case_id IS DISTINCT FROM a.id OR f.commitment_id IS DISTINCT FROM c.id OR f.request_revision IS DISTINCT FROM a.request_revision OR f.validation_run_id IS DISTINCT FROM a.validation_run_id OR f.finance_context_snapshot_id IS DISTINCT FROM a.finance_context_snapshot_id OR f.financial_analysis_run_id IS DISTINCT FROM a.financial_analysis_run_id OR f.policy_decision_run_id IS DISTINCT FROM a.policy_decision_run_id OR c.request_revision IS DISTINCT FROM a.request_revision`],
 ["payment-budget","PAYMENT_BUDGET_LINEAGE_INVALID",`SELECT count(*)::text count FROM payments p LEFT JOIN budget_commitments c ON c.id=p.commitment_id LEFT JOIN budgets b ON b.id=c.budget_id LEFT JOIN budget_versions v ON v.id=c.budget_version_id WHERE b.id IS NULL OR v.id IS NULL OR v.budget_id IS DISTINCT FROM b.id OR p.currency<>c.currency OR p.currency<>b.currency`],
 ["payment-command","PAYMENT_COMMAND_IDENTITY_INVALID",`SELECT count(*)::text count FROM payments p WHERE p.command_version<>1 OR p.command_fingerprint IS DISTINCT FROM encode(sha256(convert_to(concat_ws('|','1',p.payment_request_id::text,p.payment_date::text,p.amount_minor::text,upper(p.currency),p.payment_method,p.bank_reference_normalized,p.slip_document_id::text,'false'),'UTF8')),'hex') AND p.command_fingerprint IS DISTINCT FROM encode(sha256(convert_to(concat_ws('|','1',p.payment_request_id::text,p.payment_date::text,p.amount_minor::text,upper(p.currency),p.payment_method,p.bank_reference_normalized,p.slip_document_id::text,'true'),'UTF8')),'hex')`],
 ["payment-command-uniqueness","PAYMENT_COMMAND_IDENTITY_DUPLICATE",`SELECT count(*)::text count FROM(SELECT command_key FROM payments GROUP BY command_key HAVING count(*)<>1)x`],
 ["bank-reference-scope","BANK_REFERENCE_SCOPE_DUPLICATE",`SELECT count(*)::text count FROM(SELECT payment_method,currency,bank_reference_normalized FROM payments GROUP BY payment_method,currency,bank_reference_normalized HAVING count(*)>1)x`],
 ["budget-currency","BUDGET_CURRENCY_INCONSISTENT",`SELECT count(*)::text count FROM financial_ledger_entries l JOIN budgets b ON b.id=l.budget_id WHERE l.currency<>b.currency`],
 ["commitment-currency","COMMITMENT_CURRENCY_INCONSISTENT",`SELECT count(*)::text count FROM budget_commitments c JOIN budgets b ON b.id=c.budget_id WHERE c.currency<>b.currency`],
 ["available-equation","AVAILABLE_EQUATION_INCONSISTENT",`SELECT count(*)::text count FROM finance_context_snapshots WHERE status='COMPLETED' AND available_amount_minor IS DISTINCT FROM revised_amount_minor-actual_amount_minor-committed_amount_minor`],
 ["authoritative-available","ACTIVE_BUDGET_VERSION_INVALID",`WITH authoritative_scopes AS(SELECT b.id,b.currency,count(v.id) active_version_count,max(v.revised_amount_minor) revised_amount_minor,COALESCE((SELECT sum(l.amount_minor) FROM financial_ledger_entries l WHERE l.budget_id=b.id AND l.currency=b.currency),0) actual_amount_minor,COALESCE((SELECT sum(c.amount_minor) FROM budget_commitments c WHERE c.budget_id=b.id AND c.currency=b.currency AND c.status='ACTIVE'),0) active_commitment_amount_minor FROM budgets b LEFT JOIN budget_versions v ON v.budget_id=b.id AND v.status='ACTIVE' WHERE b.status='ACTIVE' GROUP BY b.id,b.currency),verified AS(SELECT id,currency,active_version_count,revised_amount_minor-actual_amount_minor-active_commitment_amount_minor available_amount_minor FROM authoritative_scopes)SELECT count(*)::text count FROM verified WHERE active_version_count<>1 OR available_amount_minor IS NULL`],
 ["double-reduction","PAYMENT_DOUBLE_REDUCTION_RISK",`SELECT count(*)::text count FROM payments p JOIN budget_commitments c ON c.id=p.commitment_id WHERE c.status='ACTIVE' OR c.payment_id IS DISTINCT FROM p.id`]
]}
async function countCheck(client:PoolClient,isolated:<T>(operation:()=>Promise<T>)=>Promise<T>,add:Add,name:string,code:string,sql:string){try{const count=n((await isolated(()=>client.query<CountRow>(sql))).rows[0]?.count??0);add(name,code,count===0?"PASS":"FAIL",count)}catch(error){if(error instanceof VerificationDeadlineError)throw error;add(name,`${code}_CHECK_FAILED`,"FAIL",1)}}
async function warningCount(client:PoolClient,isolated:<T>(operation:()=>Promise<T>)=>Promise<T>,add:Add,name:string,code:string,sql:string,values?:unknown[]){try{const count=n((await isolated(()=>client.query<CountRow>(sql,values))).rows[0]?.count??0);add(name,code,count?"WARNING":"PASS",count)}catch(error){if(error instanceof VerificationDeadlineError)throw error;add(name,`${code}_CHECK_FAILED`,"FAIL",1)}}
async function securityChecks(client:PoolClient,isolated:<T>(operation:()=>Promise<T>)=>Promise<T>,add:Add){for(const item of p6Checks())await countCheck(client,isolated,add,...item)}
function p6Checks():[string,string,string][]{return[
 ["p6-role-attributes","P6_ROLE_ATTRIBUTES_INVALID",`WITH expected(role_name,can_login,inherit)AS(VALUES('aims_owner',false,false),('aims_migrator',true,false),('aims_app',true,true),('aims_finance_executor',false,true),('aims_finance_runtime',true,true),('aims_payment_executor',false,true),('aims_payment_runtime',true,true),('aims_document_worker_executor',false,true),('aims_document_worker_runtime',true,true))SELECT count(*)::text count FROM expected e LEFT JOIN pg_roles r ON r.rolname=e.role_name WHERE r.oid IS NULL OR r.rolcanlogin<>e.can_login OR r.rolinherit<>e.inherit OR r.rolsuper OR r.rolcreatedb OR r.rolcreaterole OR r.rolreplication OR r.rolbypassrls`],
 ["p6-memberships","P6_ROLE_MEMBERSHIP_INVALID",`WITH expected(member_name,role_name,admin_option)AS(VALUES('aims_migrator','aims_owner',false),('aims_owner','aims_app',true),('aims_finance_executor','aims_app',false),('aims_finance_runtime','aims_finance_executor',false),('aims_payment_executor','aims_app',false),('aims_payment_runtime','aims_payment_executor',false),('aims_document_worker_runtime','aims_document_worker_executor',false)),actual AS(SELECT member.rolname member_name,role.rolname role_name,m.admin_option FROM pg_auth_members m JOIN pg_roles member ON member.oid=m.member JOIN pg_roles role ON role.oid=m.roleid WHERE member.rolname LIKE 'aims_%' AND role.rolname LIKE 'aims_%')SELECT((SELECT count(*) FROM expected e LEFT JOIN actual a USING(member_name,role_name,admin_option)WHERE a.member_name IS NULL)+(SELECT count(*) FROM actual a LEFT JOIN expected e USING(member_name,role_name,admin_option)WHERE e.member_name IS NULL))::text count`],
 ["p6-database-owner-connect","P6_DATABASE_AUTHORITY_INVALID",`SELECT(count(*) FILTER(WHERE key='owner' AND NOT ok)+count(*) FILTER(WHERE key<>'owner' AND NOT ok))::text count FROM(VALUES('owner',(SELECT pg_get_userbyid(datdba)='aims_owner' FROM pg_database WHERE datname=current_database())),('public-connect',NOT has_database_privilege('public',current_database(),'CONNECT')),('migrator-connect',has_database_privilege('aims_migrator',current_database(),'CONNECT')),('app-connect',has_database_privilege('aims_app',current_database(),'CONNECT')),('finance-connect',has_database_privilege('aims_finance_runtime',current_database(),'CONNECT')),('payment-connect',has_database_privilege('aims_payment_runtime',current_database(),'CONNECT')),('worker-connect',has_database_privilege('aims_document_worker_runtime',current_database(),'CONNECT')))v(key,ok)`],
 ["p6-schema-authority","P6_SCHEMA_AUTHORITY_INVALID",`WITH roles(role_name)AS(VALUES('aims_app'),('aims_finance_executor'),('aims_finance_runtime'),('aims_payment_executor'),('aims_payment_runtime'),('aims_document_worker_executor'),('aims_document_worker_runtime'))SELECT((SELECT count(*) FROM pg_namespace WHERE nspname='public' AND pg_get_userbyid(nspowner)<>'aims_owner')+(SELECT count(*) FROM roles WHERE NOT has_schema_privilege(role_name,'public','USAGE') OR has_schema_privilege(role_name,'public','CREATE'))+(CASE WHEN has_schema_privilege('public','public','CREATE') THEN 1 ELSE 0 END))::text count`],
 ["p6-ownership","P6_OWNERSHIP_INVALID",`SELECT((SELECT count(*) FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relkind IN('r','p','S','v','m') AND pg_get_userbyid(c.relowner)<>'aims_owner')+(SELECT count(*) FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND pg_get_userbyid(p.proowner)<>'aims_owner'))::text count`],
 ["p6-public-privileges","P6_PUBLIC_PRIVILEGE_EXPOSED",`SELECT((SELECT count(*) FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace CROSS JOIN LATERAL aclexplode(COALESCE(c.relacl,acldefault(CASE WHEN c.relkind='S' THEN 's'::"char" ELSE 'r'::"char" END,c.relowner)))a WHERE n.nspname='public' AND c.relkind IN('r','p','S') AND a.grantee=0)+(SELECT count(*) FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace CROSS JOIN LATERAL aclexplode(COALESCE(p.proacl,acldefault('f'::"char",p.proowner)))a WHERE n.nspname='public' AND a.grantee=0))::text count`],
 ["p6-security-definer","P6_SECURITY_DEFINER_INVALID",`SELECT count(*)::text count FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.prosecdef AND(pg_get_userbyid(p.proowner)<>'aims_owner' OR NOT('search_path=pg_catalog, public'=ANY(COALESCE(p.proconfig,ARRAY[]::text[]))) OR has_function_privilege('public',p.oid,'EXECUTE'))`],
 ["p6-finance-allowlist","P6_FINANCE_EXECUTOR_ALLOWLIST_INVALID",`WITH expected(signature)AS(VALUES('aims_authenticated_finance_actor()'),('complete_finance_control_pass(uuid,uuid)')),actual AS(SELECT p.oid::regprocedure::text signature FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND has_function_privilege('aims_finance_executor',p.oid,'EXECUTE'))SELECT((SELECT count(*) FROM expected e LEFT JOIN actual a USING(signature)WHERE a.signature IS NULL)+(SELECT count(*) FROM actual a LEFT JOIN expected e USING(signature)WHERE e.signature IS NULL))::text count`],
 ["p6-payment-allowlist","P6_PAYMENT_EXECUTOR_ALLOWLIST_INVALID",`WITH expected(signature)AS(VALUES('aims_authenticated_payment_actor()'),('attach_payment_slip(uuid,uuid,uuid,text,text,text,bigint,text)'),('record_payment(uuid,uuid,uuid,date,bigint,text,text,uuid,boolean)'),('begin_payment_slip_security_scan(uuid,uuid,integer,text)'),('complete_payment_slip_security_scan(uuid,uuid,integer,text,integer,text,text,text,text)')),actual AS(SELECT p.oid::regprocedure::text signature FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND has_function_privilege('aims_payment_executor',p.oid,'EXECUTE'))SELECT((SELECT count(*) FROM expected e LEFT JOIN actual a USING(signature)WHERE a.signature IS NULL)+(SELECT count(*) FROM actual a LEFT JOIN expected e USING(signature)WHERE e.signature IS NULL))::text count`],
 ["p6-worker-allowlist","P6_DOCUMENT_WORKER_ALLOWLIST_INVALID",`WITH expected(signature)AS(VALUES('claim_next_payment_document_scan(text,integer,integer,uuid)'),('complete_payment_document_scan(uuid,integer,text,integer,uuid,text,text,integer,text,text,text,text)'),('payment_document_scan_worker_health()')),actual AS(SELECT p.oid::regprocedure::text signature FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND has_function_privilege('aims_document_worker_executor',p.oid,'EXECUTE')),function_drift AS(SELECT(SELECT count(*) FROM expected e LEFT JOIN actual a USING(signature)WHERE a.signature IS NULL)+(SELECT count(*) FROM actual a LEFT JOIN expected e USING(signature)WHERE e.signature IS NULL) count)SELECT((SELECT count FROM function_drift)+(CASE WHEN has_table_privilege('aims_document_worker_runtime','payment_documents','INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER') THEN 1 ELSE 0 END)+(CASE WHEN has_function_privilege('aims_document_worker_runtime','record_payment(uuid,uuid,uuid,date,bigint,text,text,uuid,boolean)','EXECUTE') OR has_function_privilege('aims_document_worker_runtime','complete_finance_control_pass(uuid,uuid)','EXECUTE') THEN 1 ELSE 0 END))::text count`],
 ["p6-recovery-authority","P6_RECOVERY_ADVANCE_AUTHORITY_INVALID",`SELECT((CASE WHEN NOT has_function_privilege('aims_migrator','advance_aims_recovery_generation(text,uuid)','EXECUTE') THEN 1 ELSE 0 END)+(SELECT count(*) FROM(VALUES('aims_app'),('aims_finance_executor'),('aims_finance_runtime'),('aims_payment_executor'),('aims_payment_runtime'),('aims_document_worker_executor'),('aims_document_worker_runtime'))r(role_name) WHERE has_function_privilege(role_name,'advance_aims_recovery_generation(text,uuid)','EXECUTE')))::text count`],
 ["p6-default-privileges","P6_DEFAULT_PRIVILEGES_INVALID",`WITH expected(owner_name,schema_name,object_type,grantee_name,privilege_type,is_grantable)AS(VALUES('aims_owner',NULL::text,'f','aims_owner','EXECUTE',false)),actual AS(SELECT owner_role.rolname owner_name,n.nspname schema_name,d.defaclobjtype object_type,CASE WHEN a.grantee=0 THEN 'PUBLIC' ELSE grantee_role.rolname END grantee_name,a.privilege_type,a.is_grantable FROM pg_default_acl d JOIN pg_roles owner_role ON owner_role.oid=d.defaclrole LEFT JOIN pg_namespace n ON n.oid=d.defaclnamespace CROSS JOIN LATERAL aclexplode(COALESCE(d.defaclacl,'{}'::aclitem[]))a LEFT JOIN pg_roles grantee_role ON grantee_role.oid=a.grantee WHERE owner_role.rolname='aims_owner')SELECT((SELECT count(*) FROM expected e LEFT JOIN actual a ON a.owner_name=e.owner_name AND a.schema_name IS NOT DISTINCT FROM e.schema_name AND a.object_type=e.object_type AND a.grantee_name=e.grantee_name AND a.privilege_type=e.privilege_type AND a.is_grantable=e.is_grantable WHERE a.owner_name IS NULL)+(SELECT count(*) FROM actual a LEFT JOIN expected e ON a.owner_name=e.owner_name AND a.schema_name IS NOT DISTINCT FROM e.schema_name AND a.object_type=e.object_type AND a.grantee_name=e.grantee_name AND a.privilege_type=e.privilege_type AND a.is_grantable=e.is_grantable WHERE e.owner_name IS NULL))::text count`]
]}
async function residualChecks(client:PoolClient,isolated:<T>(operation:()=>Promise<T>)=>Promise<T>,add:Add){for(const item of [["stale-sessions","STALE_SESSION_PRESENT",`SELECT count(*)::text count FROM aims_sessions s CROSS JOIN aims_recovery_generation g WHERE s.revoked_at IS NULL AND s.issued_generation<>g.generation`],["stale-approval-tokens","STALE_APPROVAL_CREDENTIAL_PRESENT",`SELECT count(*)::text count FROM approval_action_tokens t CROSS JOIN aims_recovery_generation g WHERE t.status='ACTIVE' AND t.issued_generation<>g.generation`],["stale-telegram","STALE_TELEGRAM_AUTHORITY_PRESENT",`SELECT count(*)::text count FROM telegram_pending_interactions t CROSS JOIN aims_recovery_generation g WHERE t.status='PENDING' AND t.issued_generation<>g.generation`],["document-claims","STALE_DOCUMENT_CLAIM_PRESENT",`SELECT count(*)::text count FROM payment_documents d CROSS JOIN aims_recovery_generation g WHERE d.scan_claim_token IS NOT NULL AND d.scan_claim_generation<>g.generation`],["outbox-claims","STALE_OUTBOX_CLAIM_PRESENT",`SELECT count(*)::text count FROM notification_outbox o CROSS JOIN aims_recovery_generation g WHERE o.claim_token IS NOT NULL AND o.claim_generation<>g.generation`]] as [string,string,string][])await warningCount(client,isolated,add,...item);for(const status of ["PENDING","PROCESSING","FAILED_RETRYABLE","FAILED_TERMINAL"])await warningCount(client,isolated,add,`outbox-${status.toLowerCase()}`,`OUTBOX_${status}_PRESENT`,"SELECT count(*)::text count FROM notification_outbox WHERE status=$1",[status]);await warningCount(client,isolated,add,"active-document-claims","DOCUMENT_SCANNING_CLAIMS_PRESENT","SELECT count(*)::text count FROM payment_documents WHERE security_status='SCANNING'")}

async function documentChecks(client:PoolClient,isolated:<T>(operation:()=>Promise<T>)=>Promise<T>,options:RestoreCheckerOptions,add:Add,coverage:VerificationCoverage,orphan:{processed:number;orphans:number;complete:boolean},signal:AbortSignal,remaining:()=>number,objectTimeoutMs:number,documentPageSize:number,objectPageSize:number){
 try{coverage.eligible=n((await isolated(()=>client.query<CountRow>("SELECT count(*)::text count FROM payment_documents WHERE removed_at IS NULL AND security_status='CLEAN'"))).rows[0]?.count??0)}catch{add("document-coverage","DOCUMENT_ELIGIBLE_COUNT_FAILED","FAIL",1);coverage.unverified=1;return}if(!options.storage){coverage.unverified=coverage.eligible;add("document-integrity","DOCUMENT_INTEGRITY_NOT_VERIFIABLE","NOT_VERIFIABLE",coverage.eligible);return}
 let cursor:string|null=null,pages=0,remainingLimited=options.documentMode==="LIMITED"?integer(options.maxDocuments??100,1,10_000,"maxDocuments"):Number.MAX_SAFE_INTEGER;
 try{while(coverage.processed<coverage.eligible&&remainingLimited>0){remaining();if(++pages>MAX_PAGES)throw new Error("DOCUMENT_PAGINATION_SAFETY_BOUND");const size=Math.min(documentPageSize,remainingLimited),page=await isolated(()=>client.query<{id:string;storage_object_key:string;sha256:string;size_bytes:string}>("SELECT id,storage_object_key,sha256,size_bytes::text FROM payment_documents WHERE removed_at IS NULL AND security_status='CLEAN' AND($1::uuid IS NULL OR id>$1) ORDER BY id LIMIT $2",[cursor,size]));if(page.rows.length===0)break;for(const document of page.rows){remaining();cursor=document.id;coverage.processed+=1;remainingLimited-=1;try{const metadata=await boundedStorageOperation(operationSignal=>options.storage!.metadata(document.storage_object_key,operationSignal),Math.min(objectTimeoutMs,remaining()),signal);if(metadata.sha256.toLowerCase()!==document.sha256.toLowerCase()){coverage.failed+=1;add("document-integrity","CLEAN_DOCUMENT_HASH_MISMATCH","FAIL",1,document.id)}else if(metadata.sizeBytes!==n(document.size_bytes)){coverage.failed+=1;add("document-integrity","CLEAN_DOCUMENT_SIZE_MISMATCH","FAIL",1,document.id)}}catch(error){coverage.failed+=1;add("document-integrity",storageFailureCode(error,"CLEAN_DOCUMENT_OBJECT_UNAVAILABLE"),"FAIL",1,document.id)}}}}catch(error){add("document-coverage",error instanceof VerificationDeadlineError?"VERIFICATION_DEADLINE_EXCEEDED":"DOCUMENT_PAGINATION_INCOMPLETE","NOT_VERIFIABLE",1)}
 coverage.complete=coverage.mode==="FULL"&&coverage.processed===coverage.eligible&&coverage.failed===0;coverage.unverified=Math.max(0,coverage.eligible-coverage.processed);if(coverage.mode==="LIMITED")add("document-scope","DOCUMENT_VERIFICATION_LIMITED","NOT_VERIFIABLE",coverage.unverified||1);else if(!coverage.complete)add("document-coverage","FULL_DOCUMENT_COVERAGE_INCOMPLETE","NOT_VERIFIABLE",coverage.unverified+coverage.failed);else add("document-integrity","DOCUMENT_INTEGRITY_VALID","PASS",0);await enumerateOrphans(client,isolated,options.storage,add,orphan,signal,remaining,objectTimeoutMs,objectPageSize)
}
async function enumerateOrphans(client:PoolClient,isolated:<T>(operation:()=>Promise<T>)=>Promise<T>,storage:DocumentStorage,add:Add,coverage:{processed:number;orphans:number;complete:boolean},signal:AbortSignal,remaining:()=>number,objectTimeoutMs:number,pageSize:number){let cursor:string|null=null,lastKey:string|null=null,pages=0;const seenCursors=new Set<string>();try{while(true){remaining();if(++pages>MAX_PAGES)throw new Error("OBJECT_PAGINATION_SAFETY_BOUND");const page:StorageObjectPage=await boundedStorageOperation(operationSignal=>storage.listPage(cursor,pageSize,operationSignal),Math.min(objectTimeoutMs,remaining()),signal);if(page.keys.length>pageSize||page.keys.some((key:string)=>typeof key!=="string"||key.length<1||key.length>1024))throw new Error("OBJECT_PAGE_INVALID");for(let index=0;index<page.keys.length;index+=1){const key=page.keys[index];if((lastKey!==null&&key<=lastKey)||(index>0&&key<=page.keys[index-1]))throw new Error("OBJECT_ORDER_OR_DUPLICATE_INVALID");lastKey=key}coverage.processed+=page.keys.length;if(page.keys.length){const known=await isolated(()=>client.query<{storage_object_key:string}>("SELECT storage_object_key FROM payment_documents WHERE removed_at IS NULL AND storage_object_key=ANY($1::text[])",[page.keys]));coverage.orphans+=page.keys.length-new Set(known.rows.map(row=>row.storage_object_key)).size}if(page.complete){if(page.nextCursor!==null)throw new Error("OBJECT_TERMINAL_CURSOR_INVALID");coverage.complete=true;break}if(page.nextCursor===null||page.nextCursor.length>MAX_CURSOR_LENGTH||page.keys.length===0||page.nextCursor===cursor||seenCursors.has(page.nextCursor))throw new Error("OBJECT_CURSOR_INVALID");seenCursors.add(page.nextCursor);cursor=page.nextCursor}}catch(error){add("orphan-objects",storageFailureCode(error,"ORPHAN_ENUMERATION_NOT_VERIFIABLE"),"NOT_VERIFIABLE",1)}if(!coverage.complete)add("orphan-coverage","ORPHAN_COVERAGE_INCOMPLETE","NOT_VERIFIABLE",1);else add("orphan-objects","ORPHAN_OBJECT_PRESENT",coverage.orphans?"WARNING":"PASS",coverage.orphans)}
function storageFailureCode(error:unknown,fallback:string):string{return error instanceof VerificationDeadlineError?"VERIFICATION_DEADLINE_EXCEEDED":error instanceof StorageOperationTimeoutError?"STORAGE_OPERATION_TIMEOUT":error instanceof StorageOperationCleanupTimeoutError?"STORAGE_OPERATION_CLEANUP_TIMEOUT":fallback}
/** @internal Operation-scoped cancellation and bounded cleanup for recovery storage reads. */
export async function boundedStorageOperation<T>(operation:(signal:AbortSignal)=>Promise<T>,milliseconds:number,parentSignal:AbortSignal):Promise<T>{
 if(parentSignal.aborted)throw new VerificationDeadlineError();
 const controller=new AbortController();let timer:NodeJS.Timeout|undefined,parentAbort:undefined|(()=>void),timeoutWon=false;
 const completion=Promise.resolve().then(()=>operation(controller.signal)).then(value=>({status:"fulfilled" as const,value}),error=>({status:"rejected" as const,error}));
 const cancellation=new Promise<"timeout"|"parent">(resolve=>{
  timer=setTimeout(()=>{timeoutWon=true;controller.abort(new StorageOperationTimeoutError());resolve("timeout")},milliseconds);
  parentAbort=()=>{controller.abort(parentSignal.reason);resolve("parent")};parentSignal.addEventListener("abort",parentAbort,{once:true});
 });
 try{
  const winner=await Promise.race([completion,cancellation]);
  if(typeof winner!=="string"){if(winner.status==="rejected")throw winner.error;return winner.value}
  const cleanupMilliseconds=Math.min(Math.max(milliseconds,100),1_000);
  let cleanupTimer:NodeJS.Timeout|undefined;
  const cleanup=await Promise.race([completion,new Promise<"cleanup-timeout">(resolve=>{cleanupTimer=setTimeout(()=>resolve("cleanup-timeout"),cleanupMilliseconds)})]);
  if(cleanupTimer)clearTimeout(cleanupTimer);
  if(cleanup==="cleanup-timeout")throw new StorageOperationCleanupTimeoutError();
  if(winner==="parent"&&!timeoutWon)throw new VerificationDeadlineError();
  throw new StorageOperationTimeoutError();
 }finally{if(timer)clearTimeout(timer);if(parentAbort)parentSignal.removeEventListener("abort",parentAbort)}
}
async function deadlineBounded<T>(promise:Promise<T>,milliseconds:number,signal:AbortSignal,onTimeout?:()=>void):Promise<T>{if(signal.aborted)throw new VerificationDeadlineError();let timer:NodeJS.Timeout|undefined,abort:undefined|(()=>void),expired=false;const fail=()=>{if(expired)return;expired=true;onTimeout?.()};try{return await Promise.race([promise,new Promise<never>((_,reject)=>{timer=setTimeout(()=>{fail();reject(new VerificationDeadlineError())},milliseconds);abort=()=>{fail();reject(new VerificationDeadlineError())};signal.addEventListener("abort",abort,{once:true})})])}finally{if(timer)clearTimeout(timer);if(abort)signal.removeEventListener("abort",abort)}}
