import assert from "node:assert/strict";
import {createHash} from "node:crypto";
import test from "node:test";
import {CorporateAuthService,validateReturnPath} from "../src/application/auth/corporate-auth.service.js";
import {CorporateProviderTransport} from "../src/infrastructure/identity/corporate-provider-transport.js";
import {TestCorporateIdentityProvider} from "../src/infrastructure/identity/test-corporate-identity.provider.js";

const key=Buffer.alloc(32,7),request={correlationId:"123e4567-e89b-42d3-a456-426614174000"} as never,response={cookie:()=>undefined} as never;
function harness(mapped=true,generations=["generation","generation"]){
 const provider=new TestCorporateIdentityProvider(key,{AIMS_ENVIRONMENT:"test"}),queries:Array<{sql:string;values:unknown[]}>=[],events:string[]=[];let transaction:unknown[]=[],generationIndex=0;
 const query=async(sql:string,values:unknown[]=[])=>{queries.push({sql,values});if(sql.includes("create_corporate_auth_transaction")){transaction=values;return{rowCount:1,rows:[{}]}}if(sql.includes("consume_corporate_auth_transaction")){events.push("consume");return{rowCount:1,rows:[{pkce_verifier:transaction[2],nonce_digest:transaction[3],return_path:transaction[4],provider_adapter:transaction[5],expected_issuer:transaction[6]}]}}if(sql.includes("generation::text"))return{rowCount:1,rows:[{generation:generations[generationIndex++]!}]};if(sql.includes("FROM user_external_identities"))return mapped?{rowCount:2,rows:[{identity_id:"i",user_id:"u",department_id:"d",role:"REQUESTER"},{identity_id:"i",user_id:"u",department_id:"d",role:"ADMIN"}]}:{rowCount:0,rows:[]};return{rowCount:1,rows:[]}};
 const database={pool:{query},transaction:async(operation:(client:{query:typeof query})=>Promise<unknown>)=>{events.push("tx-begin");const result=await operation({query});events.push("tx-commit");return result}};
 const sessionCalls:unknown[][]=[],sessions={createCorporateSessionRecord:async(...args:unknown[])=>{events.push("session-insert");sessionCalls.push(args);return{principal:{id:"u",departmentId:"d",roles:[]},token:"token",csrf:"csrf",lifetime:300}},setCorporateSessionCookies:()=>events.push("cookie")};
 const exchange=provider.exchangeAndVerify.bind(provider);provider.exchangeAndVerify=async input=>{events.push("provider-exchange");return exchange(input)};
 return{provider,queries,sessionCalls,events,service:new CorporateAuthService(database as never,sessions as never,provider)};
}
test("initiation binds random state, S256 PKCE and nonce only through Migration060",async()=>{const a=harness(),b=harness(),ar=await a.service.initiate("/finance/dashboard",request),br=await b.service.initiate("/finance/dashboard",request),au=new URL(ar.authorizationUrl),bu=new URL(br.authorizationUrl),create=a.queries.find(q=>q.sql.includes("create_corporate_auth_transaction"))!;assert.notEqual(au.searchParams.get("state"),bu.searchParams.get("state"));assert.equal(au.searchParams.get("code_challenge_method"),"S256");assert.equal(au.searchParams.get("code_challenge"),createHash("sha256").update(String(create.values[2])).digest("base64url"));assert.equal(createHash("sha256").update(au.searchParams.get("nonce")!).digest("hex"),create.values[3]);assert.equal(JSON.stringify(a.queries).includes(au.searchParams.get("state")!),false)});
test("verified mapping durably consumes before provider I/O and emits cookies only after session commit",async()=>{const h=harness(),auth=await h.service.initiate("/requester",request),code=h.provider.issueCode({email:"shared@example.test",groups:["Finance","Admin"]}),destination=await h.service.callback(new URL(auth.authorizationUrl).searchParams.get("state")!,code,request,response),lookup=h.queries.find(q=>q.sql.includes("FROM user_external_identities"))!;assert.equal(destination,"/requester");assert.equal(h.sessionCalls.length,1);assert.deepEqual(lookup.values,["test-corporate",h.provider.expectedIssuer,"known.subject"]);assert.equal(JSON.stringify(lookup.values).includes("shared@example.test"),false);assert.deepEqual(h.events,["tx-begin","consume","tx-commit","provider-exchange","tx-begin","session-insert","tx-commit","cookie"])});
test("recovery generation change after durable consumption denies session and cookie",async()=>{const h=harness(true,["old","new"]),auth=await h.service.initiate("/",request),code=h.provider.issueCode();await assert.rejects(()=>h.service.callback(new URL(auth.authorizationUrl).searchParams.get("state")!,code,request,response),/failed/);assert.equal(h.sessionCalls.length,0);assert.equal(h.events.includes("cookie"),false)});
test("invalid signature, issuer, audience, expiry, algorithm and nonce deny",async()=>{const cases=[(p:TestCorporateIdentityProvider)=>p.issueCode()+"x",(p:TestCorporateIdentityProvider)=>p.issueCode({iss:"https://evil.example"}),(p:TestCorporateIdentityProvider)=>p.issueCode({aud:"other"}),(p:TestCorporateIdentityProvider)=>p.issueCode({exp:1}),(p:TestCorporateIdentityProvider)=>p.issueCode({alg:"none" as "HS256"}),(p:TestCorporateIdentityProvider)=>p.issueCode({nonce:"wrong"})];for(const make of cases){const h=harness(),auth=await h.service.initiate("/",request);await assert.rejects(()=>h.service.callback(new URL(auth.authorizationUrl).searchParams.get("state")!,make(h.provider),request,response),/failed/);assert.equal(h.sessionCalls.length,0)}});
test("unknown identity denies regardless of matching email or provider Finance group",async()=>{const h=harness(false),auth=await h.service.initiate("/",request),code=h.provider.issueCode({email:"known@example.test",groups:["FINANCE"]});await assert.rejects(()=>h.service.callback(new URL(auth.authorizationUrl).searchParams.get("state")!,code,request,response),/failed/);assert.equal(h.sessionCalls.length,0)});
test("return path validation denies redirect escapes",()=>{for(const value of ["https://evil.example","//evil.example","javascript:alert(1)","/\\evil","/%2f%2fevil","/%5cevil","/%3aevil"])assert.throws(()=>validateReturnPath(value),/return path/);for(const value of ["/","/finance/dashboard","/requests?id=abc&view=full"])assert.equal(validateReturnPath(value),value)});
test("cryptographic test provider cannot activate in protected environments",()=>{assert.doesNotThrow(()=>new TestCorporateIdentityProvider(key,{AIMS_ENVIRONMENT:"test"}));for(const AIMS_ENVIRONMENT of ["staging","production"])assert.throws(()=>new TestCorporateIdentityProvider(key,{NODE_ENV:"production",AIMS_ENVIRONMENT}),/FORBIDDEN/)});
test("provider transport requires TLS, bounded response, cancellation signal and no redirects",async()=>{assert.throws(()=>new CorporateProviderTransport(new URL("http://idp.example/token")),/ENDPOINT/);let options:RequestInit|undefined;const okay=new CorporateProviderTransport(new URL("https://idp.example/token"),100,1024,async(_input,init)=>{options=init;return new Response('{"ok":true}')});assert.deepEqual(await okay.postForm({code:"secret"}),{ok:true});assert.equal(options?.redirect,"error");assert.ok(options?.signal);const large=new CorporateProviderTransport(new URL("https://idp.example/token"),100,1024,async()=>new Response("x".repeat(1025)));await assert.rejects(()=>large.postForm({}),/TOO_LARGE/);const redirect=new CorporateProviderTransport(new URL("https://idp.example/token"),100,1024,async()=>new Response(null,{status:302}));await assert.rejects(()=>redirect.postForm({}),/REJECTED/);const failed=new CorporateProviderTransport(new URL("https://idp.example/token"),100,1024,async()=>{throw new Error("raw secret")});await assert.rejects(()=>failed.postForm({}),error=>error instanceof Error&&error.message==="CORPORATE_PROVIDER_REQUEST_FAILED")});
test("provider transport sanitizes a mid-response stream failure",async()=>{const body=new ReadableStream<Uint8Array>({start(controller){controller.enqueue(new TextEncoder().encode('{"partial":'));controller.error(new Error("provider socket secret"))}}),transport=new CorporateProviderTransport(new URL("https://idp.example/token"),100,1024,async()=>new Response(body));await assert.rejects(()=>transport.postForm({}),error=>error instanceof Error&&error.message==="CORPORATE_PROVIDER_REQUEST_FAILED")});
