import assert from "node:assert/strict";
import {createHash,randomBytes,randomUUID} from "node:crypto";
import test from "node:test";
import pg from "pg";

const required=(name:string)=>{const value=process.env[name];if(!value)throw new Error(`${name} is required`);return value};
const app=new pg.Pool({connectionString:required("DATABASE_URL")});
const finance=new pg.Pool({connectionString:required("FINANCE_DATABASE_URL")});
const payment=new pg.Pool({connectionString:required("PAYMENT_DATABASE_URL")});
const worker=new pg.Pool({connectionString:required("DOCUMENT_WORKER_DATABASE_URL")});
const migrator=new pg.Pool({connectionString:required("AIMS_INTEGRATION_MIGRATOR_DATABASE_URL")});
const digest=(value:string)=>createHash("sha256").update(value).digest("hex");
const verifier=()=>randomBytes(48).toString("base64url");
async function create(lifetime=300){const state=randomBytes(32).toString("base64url"),id=randomUUID();const result=await app.query("SELECT * FROM create_corporate_auth_transaction($1,$2,$3,$4,$5,$6,$7,$8,$9)",[id,digest(state),verifier(),digest(randomUUID()),"/finance/dashboard","provider-adapter","https://issuer.example.invalid",lifetime,randomUUID()]);assert.equal(result.rowCount,1);return{id,state}}
const consume=(state:string)=>app.query("SELECT * FROM consume_corporate_auth_transaction($1)",[digest(state)]);

test("correct state consumes once and wrong state and replay deny",async()=>{const transaction=await create();assert.equal((await consume(`${transaction.state}-wrong`)).rowCount,0);assert.equal((await consume(transaction.state)).rowCount,1);assert.equal((await consume(transaction.state)).rowCount,0)});
test("concurrent callbacks have exactly one consumer",async()=>{const transaction=await create();const results=await Promise.all([consume(transaction.state),consume(transaction.state)]);assert.deepEqual(results.map(value=>value.rowCount).sort(),[0,1])});
test("database expiry and recovery generation are authoritative",async()=>{const expired=await create();await migrator.query("SET ROLE aims_owner");await migrator.query("UPDATE corporate_auth_transactions SET expires_at=created_at-interval '1 second',created_at=created_at-interval '2 seconds' WHERE id=$1",[expired.id]);await migrator.query("RESET ROLE");assert.equal((await consume(expired.state)).rowCount,0);const stale=await create();await migrator.query("SELECT * FROM advance_aims_recovery_generation($1,$2)",["P13_CORPORATE_AUTH_FENCE",randomUUID()]);assert.equal((await consume(stale.state)).rowCount,0);const fresh=await create();assert.equal((await consume(fresh.state)).rowCount,1)});
test("runtime cannot read, mutate, revive, extend, rebind, or expose transaction secrets",async()=>{const transaction=await create();for(const query of ["SELECT * FROM corporate_auth_transactions","UPDATE corporate_auth_transactions SET consumed_at=NULL","UPDATE corporate_auth_transactions SET expires_at=expires_at+interval '1 hour'","UPDATE corporate_auth_transactions SET issued_generation=gen_random_uuid()"]){await assert.rejects(()=>app.query(query),/permission denied/)}for(const pool of [finance,payment,worker]){await assert.rejects(()=>pool.query("SELECT * FROM corporate_auth_transactions"),/permission denied/);await assert.rejects(()=>pool.query("SELECT * FROM consume_corporate_auth_transaction($1)",[digest(transaction.state)]),/permission denied/)}await migrator.query("SET ROLE aims_owner");const audit=await migrator.query("SELECT safe_metadata::text FROM authentication_audit_events");await migrator.query("RESET ROLE");assert.ok(!JSON.stringify(audit.rows).includes(transaction.state))});
test("stored state is digested and no token columns exist",async()=>{const transaction=await create();await migrator.query("SET ROLE aims_owner");const row=await migrator.query("SELECT state_digest,pkce_verifier,nonce_digest,issued_generation FROM corporate_auth_transactions WHERE id=$1",[transaction.id]);const columns=await migrator.query("SELECT column_name FROM information_schema.columns WHERE table_name='corporate_auth_transactions'");await migrator.query("RESET ROLE");assert.equal(row.rows[0].state_digest,digest(transaction.state));assert.notEqual(row.rows[0].state_digest,transaction.state);assert.ok(row.rows[0].pkce_verifier);assert.ok(row.rows[0].nonce_digest);assert.ok(row.rows[0].issued_generation);for(const prohibited of ["access_token","refresh_token","id_token","client_secret","authorization_code"])assert.ok(!columns.rows.some(value=>value.column_name===prohibited))});
test.after(async()=>{await Promise.all([app.end(),finance.end(),payment.end(),worker.end(),migrator.end()])});
