import assert from "node:assert/strict";
import {EventEmitter} from "node:events";
import test from "node:test";
import {httpObservabilityMiddleware,safeRouteTemplate} from "../src/infrastructure/observability/http-observability.middleware.js";
import {MetricsRegistry,metrics,observeOperation,observePaymentRecord,operationalLog,resetTelemetryLogSink,setTelemetryLogSink} from "../src/infrastructure/observability/telemetry.js";
import {WorkerHealthServer} from "../src/worker/worker-health-server.js";
import {Postgres} from "../src/infrastructure/database/postgres.js";
import {correlationMiddleware} from "../src/infrastructure/http/correlation.middleware.js";
import {safeDeliveryCode} from "../src/application/approval/approval-outbox.service.js";
import {OpenAiCompatibleProvider} from "../src/infrastructure/ai/openai-compatible-provider.js";
import {DocumentScanWorker} from "../src/worker/document-scan-worker.js";
import {TelegramApprovalChannel} from "../src/application/approval/telegram-approval.channel.js";

test("structured access logs use route templates and never bodies, headers, queries, or IDs",()=>{
  metrics.reset();const lines:string[]=[];setTelemetryLogSink(line=>lines.push(line));
  try{const response=Object.assign(new EventEmitter(),{statusCode:200});const request={method:"POST",baseUrl:"",route:{path:"/payment-requests/:id/payment"},correlationId:"safe-correlation",url:"/payment-requests/secret-id/payment?token=SECRET",body:{purpose:"PURPOSE-CANARY"},headers:{authorization:"Bearer AUTH-CANARY"}};httpObservabilityMiddleware(request as never,response as never,()=>{});response.emit("finish");const raw=lines.join("\n");assert.match(raw,/api_request_completed/);assert.match(raw,/payment-requests\/:id\/payment/);assert.doesNotMatch(raw,/secret-id|SECRET|PURPOSE-CANARY|AUTH-CANARY/)}finally{resetTelemetryLogSink()}
});
test("unknown routes normalize to one bounded series",()=>{assert.equal(safeRouteTemplate({route:undefined,baseUrl:""} as never),"UNMATCHED");const registry=new MetricsRegistry();for(let i=0;i<500;i++)registry.counter("aims_http_requests_total",{method:"GET",route:"UNMATCHED",status_class:"4XX"});assert.equal(registry.seriesCount(),1)});
test("correlation middleware preserves bounded values and replaces unsafe input",()=>{for(const supplied of ["safe.request-1","Bearer CORRELATION-CANARY",`x${"a".repeat(200)}`]){const request={header:()=>supplied} as never;const headers:Record<string,string>={};correlationMiddleware(request,{setHeader:(key:string,value:string)=>{headers[key]=value}} as never,()=>{});const value=(request as {correlationId:string}).correlationId;assert.match(value,/^[A-Za-z0-9._:-]{1,128}$/);assert.equal(headers["x-correlation-id"],value);if(supplied==="safe.request-1")assert.equal(value,supplied);else assert.notEqual(value,supplied)}});
test("cardinality attack matrix rejects request, user, document, correlation, Telegram and Payment IDs",()=>{const registry=new MetricsRegistry();for(let i=0;i<500;i++){const id=`00000000-0000-4000-8000-${String(i).padStart(12,"0")}`;for(const key of ["request_id","user_id","document_id","correlation_id","telegram_id","payment_id"])assert.equal(registry.counter("aims_domain_operations_total",{operation:"PAYMENT_RECORD",outcome:"SUCCESS",failure_category:"NONE",channel:"WEB",[key]:id} as never),false);assert.equal(registry.counter("aims_http_requests_total",{method:"GET",route:`/requests/${id}`,status_class:"2XX"}),false)}assert.equal(registry.seriesCount(),0);for(let i=0;i<500;i++)assert.equal(registry.counter("aims_http_requests_total",{method:"GET",route:"UNMATCHED",status_class:"4XX"}),true);assert.equal(registry.seriesCount(),1)});
test("central log boundary drops and redacts representative canaries",()=>{const lines:string[]=[];setTelemetryLogSink(line=>lines.push(line));try{operationalLog("error","canary_event",{operation:"PAYMENT_RECORD",status:"Bearer AUTH-CANARY",safe_error_code:"BANK-CANARY",correlation_id:"payment-evidence=EVIDENCE-CANARY",authorization:"AUTH-CANARY",cookie:"SESSION-CANARY",apiKey:"AI-KEY-CANARY",telegramToken:"BOT-CANARY",webhookSecret:"WEBHOOK-CANARY",callbackSecret:"CALLBACK-CANARY",bankReference:"BANK-CANARY",paymentEvidence:"EVIDENCE-CANARY",purpose:"PURPOSE-CANARY",payee:"PAYEE-CANARY",filename:"FILE-CANARY"})}finally{resetTelemetryLogSink()}const raw=lines.join("\n");for(const canary of ["AUTH-CANARY","SESSION-CANARY","AI-KEY-CANARY","BOT-CANARY","WEBHOOK-CANARY","CALLBACK-CANARY","BANK-CANARY","EVIDENCE-CANARY","PURPOSE-CANARY","PAYEE-CANARY","FILE-CANARY"])assert.equal(raw.includes(canary),false);assert.match(raw,/UNKNOWN/)});
test("Telegram generic provider errors cannot become telemetry or persisted raw codes",()=>{assert.equal(safeDeliveryCode(new Error("BOT-CANARY BANK-CANARY PURPOSE-CANARY")),"DELIVERY_FAILED")});
test("telemetry failure cannot change successful or failed business result",async()=>{metrics.reset();metrics.setEnabled(false);let mutations=0;assert.equal(await observeOperation("PAYMENT_RECORD","WEB","correlation",async()=>{mutations+=1;return"committed"}),"committed");assert.equal(mutations,1);await assert.rejects(()=>observeOperation("PAYMENT_RECORD","WEB","correlation",async()=>{throw new Error("domain failure")}),/domain failure/);assert.equal(mutations,1);metrics.reset()});
test("Payment authoritative outcomes remain distinct and telemetry failure cannot affect them",async()=>{metrics.reset();assert.equal(await observePaymentRecord("correlation",async report=>{report("SUCCESS");return"created"}),"created");assert.equal(await observePaymentRecord("correlation",async report=>{report("IDEMPOTENT_REPLAY");return"same"}),"same");await assert.rejects(()=>observePaymentRecord("correlation",async report=>{report("PAYLOAD_MISMATCH");throw new Error("IDEMPOTENCY_CONFLICT")}),/IDEMPOTENCY_CONFLICT/);const output=metrics.exposition();for(const outcome of ["SUCCESS","IDEMPOTENT_REPLAY","PAYLOAD_MISMATCH"])assert.match(output,new RegExp(`outcome="${outcome}"`));metrics.setEnabled(false);assert.equal(await observePaymentRecord("correlation",async report=>{report("SUCCESS");return"still-committed"}),"still-committed");metrics.reset()});
test("metrics exposition is operational-only and contains fixed types",()=>{const registry=new MetricsRegistry();registry.counter("aims_http_requests_total",{method:"GET",route:"/health/live",status_class:"2XX"});registry.histogram("aims_http_request_duration_seconds",{method:"GET",route:"/health/live"},0.01);const output=registry.exposition();assert.match(output,/# TYPE aims_http_requests_total counter/);assert.match(output,/# TYPE aims_http_request_duration_seconds histogram/);assert.doesNotMatch(output,/payee|purpose|bank_reference|correlation_id|document_id/)});
test("database transactions expose only bounded operational outcomes",async()=>{metrics.reset();const client={query:async()=>({rows:[]}),release:()=>{}};const pool={connect:async()=>client,totalCount:1,idleCount:1,waitingCount:0};const database=Object.create(Postgres.prototype) as Postgres;Object.defineProperty(database,"pool",{value:pool});assert.equal(await database.transaction(async()=>"ok"),"ok");const output=metrics.exposition();assert.match(output,/aims_db_operations_total/);assert.match(output,/operation="TRANSACTION"/);assert.doesNotMatch(output,/SELECT|password|bank_reference/) });
test("worker health exposes safe liveness, readiness, metrics, and degraded state",async()=>{metrics.reset();let ready=true;const server=new WorkerHealthServer(0,async()=>ready?{status:"ready",checks:{document_scan:{status:"ready"}}}:{status:"not_ready",checks:{document_scan:{status:"not_ready",detail:"database unavailable"}}});await server.start();try{const port=server.addressPort();assert.ok(port);assert.equal((await fetch(`http://127.0.0.1:${port}/health/live`)).status,200);assert.equal((await fetch(`http://127.0.0.1:${port}/health/ready`)).status,200);ready=false;const degraded=await fetch(`http://127.0.0.1:${port}/health/ready`);assert.equal(degraded.status,503);assert.doesNotMatch(await degraded.text(),/password|token|postgresql:\/\//i);assert.equal((await fetch(`http://127.0.0.1:${port}/metrics`)).status,200)}finally{await server.close()}});

test("authoritative document recovery result increments once without leaking scanner, filename, or content canaries",async()=>{metrics.reset();const lines:string[]=[];setTelemetryLogSink(line=>lines.push(line));let claimed=false;const pool={query:async(sql:string)=>{if(sql.includes("claim_next")){if(claimed)return{rows:[]};claimed=true;return{rows:[{document_id:"doc",payment_request_id:"request",document_version:1,document_sha256:"a".repeat(64),document_type:"INVOICE",storage_provider:"LOCAL",storage_object_key:"quarantine/FILENAME-CANARY",detected_mime_type:"application/pdf",scan_attempt:2,claim_token:"claim",lease_expires_at:new Date(),correlation_id:"safe-correlation",expired_lease_recovered:true}]}}if(sql.includes("worker_health"))return{rows:[{}]};return{rows:[{}]}}},storage={readQuarantined:async()=>new Uint8Array(Buffer.from("DOCUMENT-CONTENT-CANARY"))},scanner={scan:async()=>{throw new Error("SCANNER-RAW-CANARY FILENAME-CANARY")}};const worker=new DocumentScanWorker(pool as never,storage as never,scanner as never,{workerId:"worker",batchSize:1,leaseSeconds:5,maximumAttempts:3,retryDelaySeconds:1,pollIntervalMs:10,storageTimeoutMs:100,scannerTimeoutMs:100,shutdownGraceMs:100,telegramEnabled:false,scannerEnabled:true,documentDatabaseUrl:"unused"});try{await worker.pollBatch()}finally{resetTelemetryLogSink()}const output=metrics.exposition(),raw=lines.join("\n");assert.match(output,/aims_worker_lease_recoveries_total\{workload="DOCUMENT_SCAN"\} 1/);for(const canary of ["SCANNER-RAW-CANARY","FILENAME-CANARY","DOCUMENT-CONTENT-CANARY"])assert.equal(raw.includes(canary)||output.includes(canary),false)});

test("AI, Payment, and Telegram representative failures keep raw canaries out of telemetry",async()=>{metrics.reset();const ai=new OpenAiCompatibleProvider("AI-KEY-CANARY","model",undefined,{requestTimeoutMs:50,maxRetries:0,retryBaseDelayMs:1,maxResponseBytes:1024},{fetch:async()=>{throw new Error("AI-PROVIDER-CANARY PURPOSE-CANARY PAYEE-CANARY")},sleep:async()=>{},random:()=>0});await assert.rejects(()=>ai.diagnoseStructuredOutput());const previousFetch=globalThis.fetch;globalThis.fetch=async()=>new Response(JSON.stringify({ok:false,description:"BOT-TOKEN-CANARY CALLBACK-CANARY"}),{status:500,headers:{"content-type":"application/json"}});try{const telegram=new TelegramApprovalChannel("BOT-TOKEN-CANARY",{requestTimeoutMs:100});await assert.rejects(()=>telegram.send({chatId:"999999999",ticketNumber:"PAYMENT-ID-CANARY",amount:"123.45",currency:"MYR",purpose:"PURPOSE-CANARY",callbacks:{approve:"CALLBACK-CANARY",reject:"CALLBACK-CANARY",clarify:"CALLBACK-CANARY"}}));}finally{globalThis.fetch=previousFetch}const lines:string[]=[];setTelemetryLogSink(line=>lines.push(line));try{await assert.rejects(()=>observePaymentRecord("safe-correlation",async report=>{report("PAYLOAD_MISMATCH");throw new Error("BANK-REFERENCE-CANARY PAYMENT-EVIDENCE-CANARY")}))}finally{resetTelemetryLogSink()}const raw=`${metrics.exposition()}\n${lines.join("\n")}`;for(const canary of ["AI-KEY-CANARY","AI-PROVIDER-CANARY","PURPOSE-CANARY","PAYEE-CANARY","BOT-TOKEN-CANARY","CALLBACK-CANARY","PAYMENT-ID-CANARY","BANK-REFERENCE-CANARY","PAYMENT-EVIDENCE-CANARY","123.45","999999999"])assert.equal(raw.includes(canary),false)});
