import assert from "node:assert/strict";
import {randomUUID} from "node:crypto";
import test from "node:test";
import pg from "pg";
import type {DocumentStorage,StoredDocument,StoreDocumentInput,PromoteDocumentInput} from "../src/infrastructure/storage/document-storage.js";
import type {RecoveryManifest} from "../src/infrastructure/recovery/recovery-manifest.js";
import {runRestoreChecker} from "../src/infrastructure/recovery/restore-checker.js";

const appUrl=process.env.AIMS_INTEGRATION_MIGRATOR_DATABASE_URL,adminUrl=process.env.AIMS_INTEGRATION_ADMIN_DATABASE_URL;
if(!appUrl||!adminUrl)throw new Error("isolated application and administrator URLs are required");
const app=new pg.Pool({connectionString:appUrl}),admin=new pg.Pool({connectionString:adminUrl});
class MemoryStorage implements DocumentStorage{
  readonly objects=new Map<string,{sizeBytes:number;sha256:string}>();
  async metadata(key:string){const value=this.objects.get(key);if(!value)throw new Error("missing");return value}
  async listPage(cursor:string|null,pageSize:number){const keys=[...this.objects.keys()].sort(),start=cursor===null?0:keys.findIndex(key=>key>cursor),page=keys.slice(start<0?keys.length:start,(start<0?keys.length:start)+pageSize),complete=(start<0?keys.length:start)+page.length>=keys.length;return{keys:page,nextCursor:complete?null:page.at(-1)??null,complete}}
  async exists(key:string){return this.objects.has(key)}
  async read(key:string,expectedSha256:string):Promise<Uint8Array>{void key;void expectedSha256;throw new Error("not used")} async readQuarantined(key:string,expectedSha256:string,signal?:AbortSignal):Promise<Uint8Array>{void key;void expectedSha256;void signal;throw new Error("not used")}
  async delete(){throw new Error("read-only proof")} async storeQuarantined(input:StoreDocumentInput):Promise<StoredDocument>{void input;throw new Error("read-only proof")}
  async promoteQuarantined(input:PromoteDocumentInput):Promise<StoredDocument>{void input;throw new Error("read-only proof")}
}
const storage=new MemoryStorage();
async function generation(){return(await admin.query<{generation:string}>("SELECT generation::text FROM aims_recovery_generation WHERE singleton")).rows[0].generation}
async function manifest():Promise<RecoveryManifest>{return{specificationVersion:"1",environment:"isolated-restore",databaseRecoveryReference:"disposable-db",databaseRecoveryPoint:"2026-09-01T00:00:00Z",objectRecoveryReference:"disposable-objects",applicationRelease:"release-59",schemaVersion:59,latestMigrationId:"059_p12_recovery_generation_fencing",expectedRecoveryGeneration:await generation(),generationAdvancementEvidenceReference:"operator-advanced-generation",createdAt:"2026-09-01T01:00:00Z",integrity:{algorithm:"PROVIDER_ATTESTATION_REQUIRED",evidenceReference:"disposable-proof"}}}
async function check(overrides:Partial<Parameters<typeof runRestoreChecker>[0]>={}){return runRestoreChecker({pool:app,storage,manifest:await manifest(),runningApplicationRelease:"release-59",manifestReference:"test-manifest",...overrides})}
async function fingerprints(){const tables=["payment_requests","payments","financial_ledger_entries","budget_commitments","approval_actions","finance_control_runs","payment_documents","audit_events","aims_sessions","approval_action_tokens","notification_outbox","aims_recovery_generation","aims_recovery_generation_events"];const result:Record<string,string>={};for(const table of tables)result[table]=JSON.stringify((await admin.query<{row:string}>(`SELECT row_to_json(t)::text row FROM ${table} t ORDER BY row_to_json(t)::text`)).rows);return result}
async function generationState(){return(await admin.query<{generation:string;generation_sequence:string;advanced_at:string;reason:string;correlation_id:string}>("SELECT generation::text,generation_sequence::text,advanced_at::text,reason,correlation_id::text FROM aims_recovery_generation WHERE singleton")).rows[0]}
async function restoreGeneration(state:Awaited<ReturnType<typeof generationState>>){await admin.query("UPDATE aims_recovery_generation SET generation=$1,generation_sequence=$2,advanced_at=$3,reason=$4,correlation_id=$5 WHERE singleton",[state.generation,state.generation_sequence,state.advanced_at,state.reason,state.correlation_id])}
async function expectGenerationCorruption(sql:string,values:unknown[]=[]){const state=await generationState();try{await admin.query(sql,values);const result=await check();assert.equal(result.recoveryGeneration.status,"GENERATION_STATE_INVALID");assert.ok(result.findings.some(f=>f.code==="GENERATION_STATE_INVALID"))}finally{await restoreGeneration(state)}}
async function hydrateStorage(){storage.objects.clear();const rows=(await admin.query<{storage_object_key:string;size_bytes:string;sha256:string}>("SELECT storage_object_key,size_bytes::text,sha256 FROM payment_documents WHERE removed_at IS NULL AND security_status='CLEAN'")).rows;for(const row of rows)storage.objects.set(row.storage_object_key,{sizeBytes:Number(row.size_bytes),sha256:row.sha256})}

type FinancialGraph={request:string;payment:string;commitment:string;financeControl:string;approval:string;ledger:string;budget:string};
async function createFinancialGraph(label:string):Promise<FinancialGraph>{
 const ids={request:randomUUID(),payment:randomUUID(),commitment:randomUUID(),financeControl:randomUUID(),approval:randomUUID(),ledger:randomUUID(),validation:randomUUID(),context:randomUUID(),analysis:randomUUID(),policy:randomUUID(),document:randomUUID(),logical:randomUUID(),command:randomUUID()};
 const seed=(await admin.query<{budget:string;version:string;period:string;department:string;user_id:string;policy_set:string;policy_version:string}>(`SELECT b.id budget,v.id version,b.fiscal_period_id period,b.department_id department,u.id user_id,ps.id policy_set,pv.id policy_version FROM budgets b JOIN budget_versions v ON v.budget_id=b.id AND v.status='ACTIVE' JOIN users u ON u.id='10000000-0000-4000-8000-000000000002' JOIN policy_sets ps ON ps.status='ACTIVE' JOIN policy_versions pv ON pv.policy_set_id=ps.id AND pv.status='ACTIVE' WHERE b.status='ACTIVE' AND b.currency='MYR' ORDER BY b.id OFFSET $1 LIMIT 1`,[label==="B"?1:0])).rows[0];
 const bank=`P12${label.replaceAll(/[^A-Za-z0-9]/g,"").toUpperCase()}${ids.payment.replaceAll("-","")}`;
 await admin.query("BEGIN");
 try{
  await admin.query("SET CONSTRAINTS ALL DEFERRED");
  await admin.query(`INSERT INTO payment_requests(id,ticket_number,status,payee,purpose,category,amount,currency,department_id,due_date,payment_method,payment_details,created_by,row_version)VALUES($1,$2,'DRAFT',$3,'P12 recovery','Operations',10.00,'MYR',$4,current_date,'BANK_TRANSFER','bounded',$5,1)`,[ids.request,`P12-${ids.request.slice(0,8)}`,`P12 ${label}`,seed.department,seed.user_id]);
  await admin.query(`INSERT INTO validation_runs(id,payment_request_id,request_revision,source,status,overall_result,created_by,reviewed_by,is_current)VALUES($1,$2,1,'MANUAL','COMPLETED','PASS',$3,$3,true)`,[ids.validation,ids.request,seed.user_id]);
  await admin.query(`INSERT INTO finance_context_snapshots(id,payment_request_id,request_revision,finance_context_version,status,fiscal_period_id,fiscal_year,budget_id,budget_version_id,budget_version,department_id,category,request_currency,budget_currency,revised_amount_minor,actual_amount_minor,committed_amount_minor,available_amount_minor,request_amount_minor,projected_available_amount_minor,calculation_version,calculated_by,is_current)SELECT $1,$2,1,1,'COMPLETED',$3,extract(year from current_date)::int,$4,$5,1,$6,'Operations','MYR','MYR',1000000,0,1000,999000,1000,998000,'p12-test',$7,true`,[ids.context,ids.request,seed.period,seed.budget,seed.version,seed.department,seed.user_id]);
  await admin.query(`INSERT INTO financial_analysis_runs(id,payment_request_id,request_revision,finance_context_snapshot_id,finance_context_version,analysis_version,source,status,created_by,finalized_by,finalized_at,is_current)VALUES($1,$2,1,$3,1,1,'MANUAL','FINALIZED',$4,$4,now(),true)`,[ids.analysis,ids.request,ids.context,seed.user_id]);
  await admin.query(`INSERT INTO policy_decision_runs(id,payment_request_id,request_revision,validation_run_id,finance_context_snapshot_id,financial_analysis_run_id,policy_set_id,policy_version_id,evaluation_version,evaluated_input,result,approval_required,ready_for_approval,status,evaluated_by,is_current)VALUES($1,$2,1,$3,$4,$5,$6,$7,'p12-test','{}','PASS',false,true,'CURRENT',$8,true)`,[ids.policy,ids.request,ids.validation,ids.context,ids.analysis,seed.policy_set,seed.policy_version,seed.user_id]);
  await admin.query(`INSERT INTO approval_cases(id,payment_request_id,request_revision,validation_run_id,finance_context_snapshot_id,financial_analysis_run_id,policy_decision_run_id,policy_version_id,evidence_fingerprint,approval_plan,source,status,created_by,completed_at,is_current)VALUES($1,$2,1,$3,$4,$5,$6,$7,$8,'[]','POLICY_AUTO_APPROVAL','APPROVED',$9,now(),true)`,[ids.approval,ids.request,ids.validation,ids.context,ids.analysis,ids.policy,seed.policy_version,"a".repeat(64),seed.user_id]);
  await admin.query(`INSERT INTO budget_commitments(id,budget_id,payment_request_id,request_revision,amount_minor,currency,status,finance_context_snapshot_id,budget_version_id,approval_case_id,source,consumed_at,consumed_by,payment_id,consumption_reason)VALUES($1,$2,$3,1,1000,'MYR','CONSUMED',$4,$5,$6,'APPROVAL',now(),$7,$8,'PAYMENT_RECORDED')`,[ids.commitment,seed.budget,ids.request,ids.context,seed.version,ids.approval,seed.user_id,ids.payment]);
  await admin.query("ALTER TABLE finance_control_runs DISABLE TRIGGER USER");await admin.query(`INSERT INTO finance_control_runs(id,payment_request_id,run_version,request_revision,validation_run_id,finance_context_snapshot_id,financial_analysis_run_id,policy_decision_run_id,approval_case_id,commitment_id,evidence_fingerprint,approved_payee,approved_amount,approved_currency,approved_department_id,approved_category,approved_payment_method,approved_payment_details_hash,duplicate_status,status,is_current,started_by,finalized_by,finalized_at,completed_command_key)VALUES($1,$2,1,1,$3,$4,$5,$6,$7,$8,$9,$10,10.00,'MYR',$11,'Operations','BANK_TRANSFER',$12,'NO_DUPLICATE','PASSED',true,$13,$13,now(),$14)`,[ids.financeControl,ids.request,ids.validation,ids.context,ids.analysis,ids.policy,ids.approval,ids.commitment,"b".repeat(64),`P12 ${label}`,seed.department,"c".repeat(64),seed.user_id,randomUUID()]);await admin.query("ALTER TABLE finance_control_runs ENABLE TRIGGER USER");
  await admin.query("ALTER TABLE payment_documents DISABLE TRIGGER USER");await admin.query(`INSERT INTO payment_documents(id,payment_request_id,logical_document_id,original_filename,storage_object_key,mime_type,size_bytes,sha256,document_type,version,uploaded_by,storage_provider,declared_mime_type,detected_mime_type,security_status,scan_attempt,scan_started_at,scan_completed_at,scan_engine,scan_reference)VALUES($1,$2,$3,'slip.pdf',$4,'application/pdf',4,$5,'PAYMENT_SLIP',1,$6,'LOCAL','application/pdf','application/pdf','CLEAN',1,now(),now(),'P12','P12')`,[ids.document,ids.request,ids.logical,`active/${ids.document}`,"d".repeat(64),seed.user_id]);await admin.query("ALTER TABLE payment_documents ENABLE TRIGGER USER");
  await admin.query(`INSERT INTO payments(id,payment_request_id,finance_control_run_id,approval_case_id,commitment_id,ledger_entry_id,slip_document_id,ticket_number,payment_date,payee,department_id,category,purpose,amount_minor,currency,payment_method,bank_reference,bank_reference_normalized,recorded_by,command_key,command_version,command_fingerprint)SELECT $1::uuid,$2::uuid,$3::uuid,$4::uuid,$5::uuid,$6::uuid,$7::uuid,r.ticket_number,current_date,r.payee,r.department_id,r.category,r.purpose,1000,'MYR',r.payment_method,$8::text,$8::text,$9::uuid,$10::uuid,1,encode(sha256(convert_to(concat_ws('|','1',$2::text,current_date::text,'1000','MYR',r.payment_method,$8::text,$7::text,'false'),'UTF8')),'hex') FROM payment_requests r WHERE r.id=$2::uuid`,[ids.payment,ids.request,ids.financeControl,ids.approval,ids.commitment,ids.ledger,ids.document,bank,seed.user_id,ids.command]);
  await admin.query(`INSERT INTO financial_ledger_entries(id,budget_id,entry_type,amount_minor,currency,reference_type,reference_id,posted_at)VALUES($1,$2,'ACTUAL',1000,'MYR','PAYMENT',$3,current_date)`,[ids.ledger,seed.budget,ids.payment]);
  await admin.query("ALTER TABLE payment_requests DISABLE TRIGGER USER");await admin.query("UPDATE payment_requests SET status='PAID',row_version=2 WHERE id=$1",[ids.request]);await admin.query("ALTER TABLE payment_requests ENABLE TRIGGER USER");
  await admin.query("COMMIT");storage.objects.set(`active/${ids.document}`,{sizeBytes:4,sha256:"d".repeat(64)});return{request:ids.request,payment:ids.payment,commitment:ids.commitment,financeControl:ids.financeControl,approval:ids.approval,ledger:ids.ledger,budget:seed.budget};
 }catch(error){await admin.query("ROLLBACK");throw error}
}
async function corruptAndExpect(table:string,column:string,id:string,value:string,code:string){await admin.query(`ALTER TABLE ${table} DISABLE TRIGGER USER`);const prior=(await admin.query<{value:string}>(`SELECT ${column}::text value FROM ${table} WHERE id=$1`,[id])).rows[0].value;try{await admin.query(`UPDATE ${table} SET ${column}=$1 WHERE id=$2`,[value,id]);const result=await check();assert.ok(result.findings.some(f=>f.code===code),`${code}: ${JSON.stringify(result.findings)}`);assert.equal(result.overallStatus,"FAIL")}finally{await admin.query(`UPDATE ${table} SET ${column}=$1 WHERE id=$2`,[prior,id]);await admin.query(`ALTER TABLE ${table} ENABLE TRIGGER USER`)}}

test("healthy restored state is locally valid, generation-ready, fully covered, read-only, and requires human reconciliation",async()=>{const before=await fingerprints(),result=await check({documentPageSize:1,objectPageSize:1}),after=await fingerprints();assert.equal(result.recoveryGeneration.status,"GENERATION_READY");assert.equal(result.resumeRecommendation,"VALIDATION_PASSED_HUMAN_APPROVAL_REQUIRED",JSON.stringify(result.findings));assert.equal(result.overallStatus,"MANUAL_RECONCILIATION_REQUIRED");assert.deepEqual(after,before);assert.deepEqual(result.documentCoverage,{mode:"FULL",eligible:0,processed:0,failed:0,unverified:0,complete:true});assert.equal(result.orphanCoverage.complete,true);assert.ok(result.manualReconciliationRequirements.includes("EXTERNAL_PAYMENT_RECONCILIATION_REQUIRED"))});
test("generation mismatch reports advance required without advancing",async()=>{const before=await generation(),value=await manifest();value.expectedRecoveryGeneration=randomUUID();const result=await runRestoreChecker({pool:app,storage,manifest:value,runningApplicationRelease:"release-59",manifestReference:"test"});assert.equal(result.recoveryGeneration.status,"GENERATION_ADVANCE_REQUIRED");assert.equal(await generation(),before)});
test("CLEAN missing object and hash mismatch fail closed; orphan is never trusted",async()=>{const base=(await admin.query("SELECT id request_id,created_by user_id FROM payment_requests LIMIT 1")).rows[0];const missing=randomUUID(),wrong=randomUUID(),valid=randomUUID();for(const [id,key,sha] of [[missing,`active/${missing}`,"a".repeat(64)],[wrong,`active/${wrong}`,"b".repeat(64)],[valid,`active/${valid}`,"d".repeat(64)]])await admin.query(`INSERT INTO payment_documents(id,payment_request_id,logical_document_id,original_filename,storage_object_key,mime_type,size_bytes,sha256,document_type,version,uploaded_by,storage_provider,declared_mime_type,detected_mime_type,security_status,scan_attempt,scan_started_at,scan_completed_at,scan_engine,scan_reference) VALUES($1,$2,$3,'bounded.pdf',$4,'application/pdf',4,$5,'INVOICE',1,$6,'LOCAL','application/pdf','application/pdf','CLEAN',1,now(),now(),'TEST_SCANNER','bounded-proof')`,[id,base.request_id,randomUUID(),key,sha,base.user_id]);storage.objects.set(`active/${wrong}`,{sizeBytes:4,sha256:"c".repeat(64)});storage.objects.set(`active/${valid}`,{sizeBytes:4,sha256:"d".repeat(64)});storage.objects.set("active/orphan",{sizeBytes:4,sha256:"e".repeat(64)});const result=await check();assert.ok(result.findings.some(f=>f.code==="CLEAN_DOCUMENT_OBJECT_UNAVAILABLE"));assert.ok(result.findings.some(f=>f.code==="CLEAN_DOCUMENT_HASH_MISMATCH"));assert.ok(result.findings.some(f=>f.code==="ORPHAN_OBJECT_PRESENT"));assert.equal(result.overallStatus,"FAIL");storage.objects.clear()});
test("financial corruption is detected without repair",async()=>{const base=(await admin.query("SELECT id FROM payment_requests LIMIT 1")).rows[0];await admin.query("ALTER TABLE payment_requests DISABLE TRIGGER USER");await admin.query("UPDATE payment_requests SET status='PAID' WHERE id=$1",[base.id]);await admin.query("ALTER TABLE payment_requests ENABLE TRIGGER USER");const before=await fingerprints(),result=await check(),after=await fingerprints();assert.ok(result.findings.some(f=>f.code==="PAID_WITHOUT_EXACT_PAYMENT"));assert.deepEqual(after,before);await admin.query("ALTER TABLE payment_requests DISABLE TRIGGER USER");await admin.query("UPDATE payment_requests SET status='DRAFT' WHERE id=$1",[base.id]);await admin.query("ALTER TABLE payment_requests ENABLE TRIGGER USER")});
test("healthy authoritative financial graph passes and cross-wired lineage, currency, and command corruption fail",async()=>{
 const a=await createFinancialGraph("A"),b=await createFinancialGraph("B");await hydrateStorage();let result=await check();assert.ok(!result.findings.some(f=>f.code.startsWith("PAYMENT_")||f.code.startsWith("BANK_REFERENCE")||f.code.startsWith("AUTHORITATIVE_AVAILABLE")),JSON.stringify(result.findings));
 const wrongCommitment=randomUUID();await admin.query(`INSERT INTO budget_commitments(id,budget_id,payment_request_id,request_revision,amount_minor,currency,status,finance_context_snapshot_id,budget_version_id,approval_case_id,source,consumed_at,consumed_by,payment_id,consumption_reason)SELECT $1,budget_id,payment_request_id,request_revision,amount_minor,currency,status,finance_context_snapshot_id,budget_version_id,NULL,source,consumed_at,consumed_by,payment_id,consumption_reason FROM budget_commitments WHERE id=$2`,[wrongCommitment,b.commitment]);
 await corruptAndExpect("payments","commitment_id",a.payment,wrongCommitment,"PAYMENT_COMMITMENT_INCONSISTENT");await admin.query("DELETE FROM budget_commitments WHERE id=$1",[wrongCommitment]);
 await corruptAndExpect("payments","finance_control_run_id",a.payment,b.financeControl,"PAYMENT_LINEAGE_INVALID");
 await corruptAndExpect("payments","approval_case_id",a.payment,b.approval,"PAYMENT_COMMITMENT_INCONSISTENT");
 await corruptAndExpect("financial_ledger_entries","budget_id",a.ledger,b.budget,"PAYMENT_LEDGER_INCONSISTENT");
 const wrongLedger=randomUUID();await admin.query(`INSERT INTO financial_ledger_entries(id,budget_id,entry_type,amount_minor,currency,reference_type,reference_id,posted_at)SELECT $1,budget_id,entry_type,amount_minor,currency,reference_type,$3,posted_at FROM financial_ledger_entries WHERE id=$2`,[wrongLedger,b.ledger,randomUUID()]);await corruptAndExpect("payments","ledger_entry_id",a.payment,wrongLedger,"PAYMENT_LEDGER_INCONSISTENT");await admin.query("ALTER TABLE financial_ledger_entries DISABLE TRIGGER USER");await admin.query("DELETE FROM financial_ledger_entries WHERE id=$1",[wrongLedger]);await admin.query("ALTER TABLE financial_ledger_entries ENABLE TRIGGER USER");
 await corruptAndExpect("finance_control_runs","is_current",a.financeControl,"false","PAYMENT_LINEAGE_INVALID");
 await corruptAndExpect("payments","currency",a.payment,"USD","PAYMENT_REQUEST_STATE_INVALID");
 await corruptAndExpect("payments","command_fingerprint",a.payment,"0".repeat(64),"PAYMENT_COMMAND_IDENTITY_INVALID");
 await corruptAndExpect("payments","payment_request_id",a.payment,"73000000-0000-4000-8000-000000000001","PAYMENT_REQUEST_STATE_INVALID");
 result=await check();assert.equal(result.overallStatus,"MANUAL_RECONCILIATION_REQUIRED");assert.ok(!JSON.stringify(result).includes("P12A"));
});
test("reverse Payment ledger and consumed-commitment bijections detect orphan, mismatch, extra, request, amount, and currency corruption",async()=>{
 const payment=(await admin.query<FinancialGraph>(`SELECT p.id payment,p.payment_request_id request,p.commitment_id commitment,p.ledger_entry_id ledger,p.finance_control_run_id "financeControl",p.approval_case_id approval,c.budget_id budget FROM payments p JOIN budget_commitments c ON c.id=p.commitment_id ORDER BY p.id LIMIT 1`)).rows[0];
 const expect=async(code:string)=>{const result=await check();assert.ok(result.findings.some(f=>f.code===code),`${code}: ${JSON.stringify(result.findings)}`);assert.equal(result.overallStatus,"FAIL")};
 const orphanLedger=randomUUID();await admin.query(`INSERT INTO financial_ledger_entries(id,budget_id,entry_type,amount_minor,currency,reference_type,reference_id,posted_at)SELECT $1,budget_id,'ACTUAL',amount_minor,currency,'PAYMENT',$2,posted_at FROM financial_ledger_entries WHERE id=$3`,[orphanLedger,randomUUID(),payment.ledger]);try{await expect("REVERSE_PAYMENT_LEDGER_INCONSISTENT")}finally{await admin.query("ALTER TABLE financial_ledger_entries DISABLE TRIGGER USER");await admin.query("DELETE FROM financial_ledger_entries WHERE id=$1",[orphanLedger]);await admin.query("ALTER TABLE financial_ledger_entries ENABLE TRIGGER USER")}
 const reverseLedger=randomUUID(),oldReference=(await admin.query<{reference_id:string}>("SELECT reference_id::text FROM financial_ledger_entries WHERE id=$1",[payment.ledger])).rows[0].reference_id;await admin.query("ALTER TABLE financial_ledger_entries DISABLE TRIGGER USER");try{await admin.query("UPDATE financial_ledger_entries SET reference_id=$1 WHERE id=$2",[randomUUID(),payment.ledger]);await admin.query(`INSERT INTO financial_ledger_entries(id,budget_id,entry_type,amount_minor,currency,reference_type,reference_id,posted_at)SELECT $1,budget_id,'ACTUAL',amount_minor,currency,'PAYMENT',$2,posted_at FROM financial_ledger_entries WHERE id=$3`,[reverseLedger,payment.payment,payment.ledger]);await expect("REVERSE_PAYMENT_LEDGER_INCONSISTENT")}finally{await admin.query("DELETE FROM financial_ledger_entries WHERE id=$1",[reverseLedger]);await admin.query("UPDATE financial_ledger_entries SET reference_id=$1 WHERE id=$2",[oldReference,payment.ledger]);await admin.query("ALTER TABLE financial_ledger_entries ENABLE TRIGGER USER")}
 const extraLedger=randomUUID(),ledgerUnique=(await admin.query<{name:string}>(`SELECT conname name FROM pg_constraint WHERE conrelid='financial_ledger_entries'::regclass AND contype='u' AND pg_get_constraintdef(oid) LIKE '%reference_type, reference_id, entry_type%'`)).rows[0].name;if(!/^[a-z0-9_]+$/.test(ledgerUnique))throw new Error("unexpected disposable constraint name");await admin.query(`ALTER TABLE financial_ledger_entries DROP CONSTRAINT "${ledgerUnique}"`);try{await admin.query(`INSERT INTO financial_ledger_entries(id,budget_id,entry_type,amount_minor,currency,reference_type,reference_id,posted_at)SELECT $1,budget_id,'ACTUAL',amount_minor,currency,'PAYMENT',reference_id,posted_at FROM financial_ledger_entries WHERE id=$2`,[extraLedger,payment.ledger]);await expect("REVERSE_PAYMENT_LEDGER_INCONSISTENT")}finally{await admin.query("ALTER TABLE financial_ledger_entries DISABLE TRIGGER USER");await admin.query("DELETE FROM financial_ledger_entries WHERE id=$1",[extraLedger]);await admin.query("ALTER TABLE financial_ledger_entries ENABLE TRIGGER USER");await admin.query(`ALTER TABLE financial_ledger_entries ADD CONSTRAINT "${ledgerUnique}" UNIQUE(reference_type,reference_id,entry_type)`)}
 const orphanCommitment=randomUUID();await admin.query("ALTER TABLE budget_commitments DISABLE TRIGGER ALL");try{await admin.query(`INSERT INTO budget_commitments(id,budget_id,payment_request_id,request_revision,amount_minor,currency,status,finance_context_snapshot_id,budget_version_id,approval_case_id,source,consumed_at,consumed_by,payment_id,consumption_reason)SELECT $1,budget_id,payment_request_id,request_revision,amount_minor,currency,'CONSUMED',finance_context_snapshot_id,budget_version_id,NULL,'APPROVAL',now(),consumed_by,$2,'PAYMENT_RECORDED' FROM budget_commitments WHERE id=$3`,[orphanCommitment,randomUUID(),payment.commitment]);await expect("REVERSE_PAYMENT_COMMITMENT_INCONSISTENT")}finally{await admin.query("DELETE FROM budget_commitments WHERE id=$1",[orphanCommitment]);await admin.query("ALTER TABLE budget_commitments ENABLE TRIGGER ALL")}
 await admin.query("ALTER TABLE budget_commitments DISABLE TRIGGER ALL");try{await admin.query("UPDATE budget_commitments SET payment_id=NULL WHERE id=$1",[payment.commitment]);await expect("REVERSE_PAYMENT_COMMITMENT_INCONSISTENT")}finally{await admin.query("UPDATE budget_commitments SET payment_id=$1 WHERE id=$2",[payment.payment,payment.commitment]);await admin.query("ALTER TABLE budget_commitments ENABLE TRIGGER ALL")}
 const reverseCommitment=randomUUID(),other=(await admin.query<FinancialGraph>(`SELECT p.id payment,p.payment_request_id request,p.commitment_id commitment,p.ledger_entry_id ledger,p.finance_control_run_id "financeControl",p.approval_case_id approval,c.budget_id budget FROM payments p JOIN budget_commitments c ON c.id=p.commitment_id WHERE p.id<>$1 LIMIT 1`,[payment.payment])).rows[0];await admin.query(`INSERT INTO budget_commitments(id,budget_id,payment_request_id,request_revision,amount_minor,currency,status,finance_context_snapshot_id,budget_version_id,approval_case_id,source,consumed_at,consumed_by,payment_id,consumption_reason)SELECT $1,budget_id,$2,request_revision,amount_minor,currency,'CONSUMED',finance_context_snapshot_id,budget_version_id,NULL,'APPROVAL',now(),consumed_by,$3,'PAYMENT_RECORDED' FROM budget_commitments WHERE id=$4`,[reverseCommitment,other.request,payment.payment,payment.commitment]);try{await expect("REVERSE_PAYMENT_COMMITMENT_INCONSISTENT");await admin.query("ALTER TABLE budget_commitments DISABLE TRIGGER USER");await admin.query("UPDATE budget_commitments SET amount_minor=amount_minor+1,currency='USD' WHERE id=$1",[reverseCommitment]);await admin.query("ALTER TABLE budget_commitments ENABLE TRIGGER USER");await expect("REVERSE_PAYMENT_COMMITMENT_INCONSISTENT")}finally{await admin.query("DELETE FROM budget_commitments WHERE id=$1",[reverseCommitment])}
 const healthy=await check();assert.equal(healthy.overallStatus,"MANUAL_RECONCILIATION_REQUIRED",JSON.stringify(healthy.findings));
});
test("authoritative Available starts from every active budget and rejects missing or multiple active versions",async()=>{
 const scope=(await admin.query<{budget:string;version:string}>("SELECT b.id budget,v.id version FROM budgets b JOIN budget_versions v ON v.budget_id=b.id AND v.status='ACTIVE' WHERE b.status='ACTIVE' ORDER BY b.id LIMIT 1")).rows[0];
 const expectInvalid=async()=>{const result=await check();assert.ok(result.findings.some(f=>f.code==="ACTIVE_BUDGET_VERSION_INVALID"),JSON.stringify(result.findings));assert.equal(result.overallStatus,"FAIL")};
 await admin.query("UPDATE budget_versions SET status='SUPERSEDED' WHERE id=$1",[scope.version]);try{await expectInvalid()}finally{await admin.query("UPDATE budget_versions SET status='ACTIVE' WHERE id=$1",[scope.version])}
 const duplicate=randomUUID();await admin.query("DROP INDEX budget_versions_one_active_idx");try{await admin.query(`INSERT INTO budget_versions(id,budget_id,version,original_amount_minor,revised_amount_minor,effective_from,status)SELECT $1,budget_id,(SELECT max(version)+1 FROM budget_versions WHERE budget_id=$2),original_amount_minor,revised_amount_minor,effective_from,'ACTIVE' FROM budget_versions WHERE id=$3`,[duplicate,scope.budget,scope.version]);await expectInvalid()}finally{await admin.query("DELETE FROM budget_versions WHERE id=$1",[duplicate]);await admin.query("CREATE UNIQUE INDEX budget_versions_one_active_idx ON budget_versions(budget_id) WHERE status='ACTIVE'")}
 const result=await check(),available=result.checks.find(item=>item.name==="authoritative-available");assert.deepEqual(available,{name:"authoritative-available",status:"PASS",count:0});
 const components=await admin.query<{revised:string;actual:string;active:string;available:string}>(`SELECT v.revised_amount_minor::text revised,COALESCE((SELECT sum(amount_minor) FROM financial_ledger_entries WHERE budget_id=b.id AND currency=b.currency),0)::text actual,COALESCE((SELECT sum(amount_minor) FROM budget_commitments WHERE budget_id=b.id AND currency=b.currency AND status='ACTIVE'),0)::text active,(v.revised_amount_minor-COALESCE((SELECT sum(amount_minor) FROM financial_ledger_entries WHERE budget_id=b.id AND currency=b.currency),0)-COALESCE((SELECT sum(amount_minor) FROM budget_commitments WHERE budget_id=b.id AND currency=b.currency AND status='ACTIVE'),0))::text available FROM budgets b JOIN budget_versions v ON v.budget_id=b.id AND v.status='ACTIVE' WHERE b.id=$1`,[scope.budget]);assert.equal(BigInt(components.rows[0].available),BigInt(components.rows[0].revised)-BigInt(components.rows[0].actual)-BigInt(components.rows[0].active));
});
test("bank-reference verification uses the database-authoritative method/currency/normalized scope",async()=>{const index=await admin.query<{definition:string}>("SELECT pg_get_indexdef(indexrelid) definition FROM pg_index WHERE indexrelid='payments_scoped_bank_reference_idx'::regclass AND indisunique");assert.equal(index.rowCount,1);assert.match(index.rows[0].definition,/payment_method, currency, bank_reference_normalized/);const result=await check();assert.ok(result.checks.some(c=>c.name==="bank-reference-scope"&&c.status==="PASS"));assert.ok(!JSON.stringify(result).includes("bank_reference"))});

test("restored P6 catalog verification fails representative privilege-manifest drift without repair",async()=>{
 const expect=async(code:string,mutate:string,restore:string)=>{await admin.query(mutate);try{const result=await check();assert.ok(result.findings.some(f=>f.code===code),`${code}: ${JSON.stringify(result.findings)}`);assert.equal(result.overallStatus,"FAIL")}finally{await admin.query(restore)}};
 await expect("P6_ROLE_ATTRIBUTES_INVALID","ALTER ROLE aims_app CREATEDB","ALTER ROLE aims_app NOCREATEDB");
 await expect("P6_ROLE_MEMBERSHIP_INVALID","GRANT aims_payment_executor TO aims_finance_runtime","REVOKE aims_payment_executor FROM aims_finance_runtime");
 await expect("P6_DATABASE_AUTHORITY_INVALID",`GRANT CONNECT ON DATABASE ${process.env.AIMS_INTEGRATION_DATABASE} TO PUBLIC`,`REVOKE CONNECT ON DATABASE ${process.env.AIMS_INTEGRATION_DATABASE} FROM PUBLIC`);
 await expect("P6_SCHEMA_AUTHORITY_INVALID","GRANT CREATE ON SCHEMA public TO aims_app","REVOKE CREATE ON SCHEMA public FROM aims_app");
 await expect("P6_OWNERSHIP_INVALID","ALTER TABLE authentication_audit_events OWNER TO postgres","ALTER TABLE authentication_audit_events OWNER TO aims_owner");
 await expect("P6_PUBLIC_PRIVILEGE_EXPOSED","GRANT SELECT ON authentication_audit_events TO PUBLIC","REVOKE SELECT ON authentication_audit_events FROM PUBLIC");
 await expect("P6_FINANCE_EXECUTOR_ALLOWLIST_INVALID","GRANT EXECUTE ON FUNCTION advance_aims_recovery_generation(text,uuid) TO aims_finance_executor","REVOKE EXECUTE ON FUNCTION advance_aims_recovery_generation(text,uuid) FROM aims_finance_executor");
 await expect("P6_FINANCE_EXECUTOR_ALLOWLIST_INVALID","REVOKE EXECUTE ON FUNCTION complete_finance_control_pass(uuid,uuid) FROM aims_finance_executor","GRANT EXECUTE ON FUNCTION complete_finance_control_pass(uuid,uuid) TO aims_finance_executor");
 await expect("P6_PAYMENT_EXECUTOR_ALLOWLIST_INVALID","GRANT EXECUTE ON FUNCTION advance_aims_recovery_generation(text,uuid) TO aims_payment_executor","REVOKE EXECUTE ON FUNCTION advance_aims_recovery_generation(text,uuid) FROM aims_payment_executor");
 await expect("P6_PAYMENT_EXECUTOR_ALLOWLIST_INVALID","REVOKE EXECUTE ON FUNCTION record_payment(uuid,uuid,uuid,date,bigint,text,text,uuid,boolean) FROM aims_payment_executor","GRANT EXECUTE ON FUNCTION record_payment(uuid,uuid,uuid,date,bigint,text,text,uuid,boolean) TO aims_payment_executor");
 await expect("P6_DOCUMENT_WORKER_ALLOWLIST_INVALID","REVOKE EXECUTE ON FUNCTION claim_next_payment_document_scan(text,integer,integer,uuid) FROM aims_document_worker_executor","GRANT EXECUTE ON FUNCTION claim_next_payment_document_scan(text,integer,integer,uuid) TO aims_document_worker_executor");
 await expect("P6_RECOVERY_ADVANCE_AUTHORITY_INVALID","GRANT EXECUTE ON FUNCTION advance_aims_recovery_generation(text,uuid) TO aims_app","REVOKE EXECUTE ON FUNCTION advance_aims_recovery_generation(text,uuid) FROM aims_app");
 await expect("P6_RECOVERY_ADVANCE_AUTHORITY_INVALID","REVOKE EXECUTE ON FUNCTION advance_aims_recovery_generation(text,uuid) FROM aims_migrator","GRANT EXECUTE ON FUNCTION advance_aims_recovery_generation(text,uuid) TO aims_migrator");
 await expect("P6_SECURITY_DEFINER_INVALID","ALTER FUNCTION aims_authenticated_payment_actor() SET search_path=public","ALTER FUNCTION aims_authenticated_payment_actor() SET search_path=pg_catalog,public");
 await admin.query("SET ROLE aims_owner;CREATE SEQUENCE p12_disposable_acl_sequence;RESET ROLE");try{await expect("P6_PUBLIC_PRIVILEGE_EXPOSED","GRANT USAGE ON SEQUENCE p12_disposable_acl_sequence TO PUBLIC","REVOKE USAGE ON SEQUENCE p12_disposable_acl_sequence FROM PUBLIC")}finally{await admin.query("SET ROLE aims_owner;DROP SEQUENCE p12_disposable_acl_sequence;RESET ROLE")}
 await expect("P6_DEFAULT_PRIVILEGES_INVALID","SET ROLE aims_owner;ALTER DEFAULT PRIVILEGES GRANT EXECUTE ON FUNCTIONS TO PUBLIC;RESET ROLE","SET ROLE aims_owner;ALTER DEFAULT PRIVILEGES REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;RESET ROLE");
 await expect("P6_DEFAULT_PRIVILEGES_INVALID","SET ROLE aims_owner;ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO aims_app;RESET ROLE","SET ROLE aims_owner;ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE SELECT ON TABLES FROM aims_app;RESET ROLE");
 await expect("P6_DEFAULT_PRIVILEGES_INVALID","SET ROLE aims_owner;ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO aims_app WITH GRANT OPTION;RESET ROLE","SET ROLE aims_owner;ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE SELECT ON TABLES FROM aims_app;RESET ROLE");
 await expect("P6_DEFAULT_PRIVILEGES_INVALID","SET ROLE aims_owner;ALTER DEFAULT PRIVILEGES REVOKE EXECUTE ON FUNCTIONS FROM aims_owner;RESET ROLE","SET ROLE aims_owner;ALTER DEFAULT PRIVILEGES GRANT EXECUTE ON FUNCTIONS TO aims_owner;RESET ROLE");
 const healthy=await check();assert.equal(healthy.overallStatus,"MANUAL_RECONCILIATION_REQUIRED",JSON.stringify(healthy.findings));
});
test("detailed findings are bounded while aggregate counts remain",async()=>{const value=await manifest();value.expectedRecoveryGeneration=randomUUID();value.applicationRelease="different";const result=await runRestoreChecker({pool:app,storage,manifest:value,runningApplicationRelease:"release-59",manifestReference:"test",maxDetailedFindings:1,documentMode:"LIMITED",maxDocuments:1});assert.equal(result.findings.length,1);assert.equal(result.truncated,true);assert.ok(result.aggregateFindingCount>1)});

test("generation singleton must exactly match UUID, correlation, timestamp, and sequence event",async()=>{
 await expectGenerationCorruption("UPDATE aims_recovery_generation SET generation=$1 WHERE singleton",[randomUUID()]);
 await expectGenerationCorruption("UPDATE aims_recovery_generation SET correlation_id=$1 WHERE singleton",[randomUUID()]);
 await expectGenerationCorruption("UPDATE aims_recovery_generation SET advanced_at=advanced_at+interval '1 second' WHERE singleton");
 await expectGenerationCorruption("UPDATE aims_recovery_generation SET generation_sequence=generation_sequence+1 WHERE singleton");
});
test("missing current generation event fails closed",async()=>{const state=await generationState();await admin.query("ALTER TABLE aims_recovery_generation_events DISABLE TRIGGER aims_recovery_generation_events_append_only");try{await admin.query("DELETE FROM aims_recovery_generation_events WHERE generation_sequence=$1",[state.generation_sequence]);const result=await check();assert.equal(result.recoveryGeneration.status,"GENERATION_STATE_INVALID")}finally{await admin.query("INSERT INTO aims_recovery_generation_events(generation_sequence,generation,advanced_at,reason,correlation_id)VALUES($1,$2,$3,$4,$5)",[state.generation_sequence,state.generation,state.advanced_at,state.reason,state.correlation_id]);await admin.query("ALTER TABLE aims_recovery_generation_events ENABLE TRIGGER aims_recovery_generation_events_append_only")}});

test("FULL verification paginates multiple pages including a final partial page with accurate coverage",async()=>{await hydrateStorage();const result=await check({documentPageSize:2,objectPageSize:2});assert.ok(result.documentCoverage.eligible>=5);assert.equal(result.documentCoverage.processed,result.documentCoverage.eligible);assert.equal(result.documentCoverage.failed,0);assert.equal(result.documentCoverage.unverified,0);assert.equal(result.documentCoverage.complete,true);assert.equal(result.orphanCoverage.complete,true)});
test("later object page failure and cursor anomalies make orphan coverage incomplete",async()=>{await hydrateStorage();let calls=0;const failing=new Proxy(storage,{get(target,property,receiver){if(property==="listPage")return async()=>{calls+=1;if(calls===2)throw new Error("provider credential do-not-echo");return{keys:["active/a"],nextCursor:"cursor-1",complete:false}};return Reflect.get(target,property,receiver)}});let result=await check({storage:failing,objectPageSize:1});assert.equal(result.orphanCoverage.complete,false);assert.ok(result.findings.some(f=>f.code==="ORPHAN_ENUMERATION_NOT_VERIFIABLE"));const looping=new Proxy(storage,{get(target,property,receiver){if(property==="listPage")return async()=>({keys:["active/a"],nextCursor:"same",complete:false});return Reflect.get(target,property,receiver)}});result=await check({storage:looping,objectPageSize:1});assert.equal(result.orphanCoverage.complete,false);assert.ok(!JSON.stringify(result).includes("do-not-echo"))});
test("duplicate object keys across pages fail closed",async()=>{await hydrateStorage();let calls=0;const duplicate=new Proxy(storage,{get(target,property,receiver){if(property==="listPage")return async()=>{calls+=1;return calls===1?{keys:["active/a"],nextCursor:"next",complete:false}:{keys:["active/a"],nextCursor:null,complete:true}};return Reflect.get(target,property,receiver)}});const result=await check({storage:duplicate,objectPageSize:1});assert.equal(result.orphanCoverage.complete,false);assert.equal(result.overallStatus,"FAIL")});
test("per-operation listPage timeout aborts the operation and awaits cleanup before returning",async()=>{await hydrateStorage();let consumed=0,settled=false,aborted=false;const timed=new Proxy(storage,{get(target,property,receiver){if(property==="listPage")return async(_cursor:string|null,_pageSize:number,signal?:AbortSignal)=>{try{for(let index=0;index<10_000;index+=1){await new Promise(resolve=>setTimeout(resolve,2));if(signal?.aborted){aborted=true;throw new Error("enumeration aborted")}consumed+=1}return{keys:[],nextCursor:null,complete:true}}finally{settled=true}};return Reflect.get(target,property,receiver)}});const result=await check({storage:timed,documentTimeoutMs:100,overallTimeoutMs:2_000});assert.equal(aborted,true);assert.equal(settled,true);assert.ok(consumed<100);assert.equal(result.orphanCoverage.complete,false);assert.equal(result.overallStatus,"FAIL");assert.ok(result.findings.some(f=>f.code==="STORAGE_OPERATION_TIMEOUT"));const stoppedAt=consumed;await new Promise(resolve=>setTimeout(resolve,20));assert.equal(consumed,stoppedAt)});
test("per-operation metadata timeout propagates abort and awaits object-read cleanup",async()=>{await hydrateStorage();let calls=0,aborted=false,settled=false;const timed=new Proxy(storage,{get(target,property,receiver){if(property==="metadata")return async(key:string,signal?:AbortSignal)=>{calls+=1;if(calls>1)return target.metadata(key);try{while(!signal?.aborted)await new Promise(resolve=>setTimeout(resolve,2));aborted=true;throw new Error("metadata aborted")}finally{settled=true}};return Reflect.get(target,property,receiver)}});const result=await check({storage:timed,documentTimeoutMs:100,overallTimeoutMs:2_000});assert.equal(aborted,true);assert.equal(settled,true);assert.equal(result.documentCoverage.complete,false);assert.equal(result.overallStatus,"FAIL");assert.ok(result.findings.some(f=>f.code==="STORAGE_OPERATION_TIMEOUT"))});
test("overall tool deadline aborts incomplete FULL verification and cannot pass",async()=>{await hydrateStorage();const slow=new Proxy(storage,{get(target,property,receiver){if(property==="metadata")return async()=>new Promise(resolve=>setTimeout(()=>resolve({sizeBytes:4,sha256:"a".repeat(64)}),250));return Reflect.get(target,property,receiver)}});const result=await check({storage:slow,overallTimeoutMs:100,documentTimeoutMs:500});assert.equal(result.documentCoverage.complete,false);assert.equal(result.overallStatus,"FAIL");assert.ok(result.findings.some(f=>f.code==="VERIFICATION_DEADLINE_EXCEEDED"))});
test("operator cancellation aborts incomplete FULL verification",async()=>{await hydrateStorage();const controller=new AbortController();controller.abort();const result=await check({signal:controller.signal});assert.equal(result.documentCoverage.complete,false);assert.equal(result.overallStatus,"FAIL");assert.ok(result.findings.some(f=>f.code==="VERIFICATION_CANCELLED"))});

function poolWithFailure(pattern:RegExp):pg.Pool{let failed=false;return{connect:async()=>{const client=await app.connect();return new Proxy(client,{get(target,property){if(property==="query")return async(...args:unknown[])=>{const sql=typeof args[0]==="string"?args[0]:"";if(!failed&&pattern.test(sql)){failed=true;throw new Error("injected safe failure")}return(target.query as (...queryArgs:unknown[])=>unknown).apply(target,args)};const value=Reflect.get(target,property);return typeof value==="function"?value.bind(target):value}})}} as unknown as pg.Pool}
function poolWithNthFailure(pattern:RegExp,nth:number):pg.Pool{let matches=0;return{connect:async()=>{const client=await app.connect();return new Proxy(client,{get(target,property){if(property==="query")return async(...args:unknown[])=>{const sql=typeof args[0]==="string"?args[0]:"";if(pattern.test(sql)&&++matches===nth)throw new Error("injected later page failure");return(target.query as(...queryArgs:unknown[])=>unknown).apply(target,args)};const value=Reflect.get(target,property);return typeof value==="function"?value.bind(target):value}})}} as unknown as pg.Pool}
function poolWithDelayedQuery(pattern:RegExp,seconds:number):pg.Pool{return{connect:async()=>{const client=await app.connect();return new Proxy(client,{get(target,property){if(property==="query")return async(...args:unknown[])=>{const sql=typeof args[0]==="string"?args[0]:"";if(pattern.test(sql))return target.query("SELECT pg_sleep($1)",[seconds]);return(target.query as(...queryArgs:unknown[])=>unknown).apply(target,args)};const value=Reflect.get(target,property);return typeof value==="function"?value.bind(target):value}})}} as unknown as pg.Pool}
test("later CLEAN document page failure makes FULL coverage incomplete",async()=>{await hydrateStorage();const result=await runRestoreChecker({pool:poolWithNthFailure(/SELECT id,storage_object_key,sha256/,2),storage,manifest:await manifest(),runningApplicationRelease:"release-59",manifestReference:"test",documentPageSize:2});assert.equal(result.documentCoverage.complete,false);assert.ok(result.findings.some(f=>f.code==="DOCUMENT_PAGINATION_INCOMPLETE"));assert.equal(result.overallStatus,"FAIL")});
test("worker residual failure does not suppress outbox checks",async()=>{await hydrateStorage();const result=await runRestoreChecker({pool:poolWithFailure(/scan_claim_token IS NOT NULL/),storage,manifest:await manifest(),runningApplicationRelease:"release-59",manifestReference:"test"});assert.ok(result.findings.some(f=>f.code==="STALE_DOCUMENT_CLAIM_PRESENT_CHECK_FAILED"));assert.ok(result.checks.some(check=>check.name==="outbox-pending"));assert.equal(result.overallStatus,"FAIL")});
test("outbox query failure preserves earlier evidence and later independent checks",async()=>{await hydrateStorage();const result=await runRestoreChecker({pool:poolWithFailure(/notification_outbox WHERE status=\$1/),storage,manifest:await manifest(),runningApplicationRelease:"release-59",manifestReference:"test"});assert.ok(result.findings.some(f=>f.code==="OUTBOX_PENDING_PRESENT_CHECK_FAILED"));assert.ok(result.checks.some(check=>check.name==="outbox-processing"));assert.ok(result.checks.some(check=>check.name==="active-document-claims"));assert.equal(result.overallStatus,"FAIL")});
test("connection acquisition cannot outlive the authoritative checker deadline",async()=>{let released=0;const delayed={connect:()=>new Promise<pg.PoolClient>(resolve=>setTimeout(()=>resolve({release:()=>{released+=1}} as unknown as pg.PoolClient),250))} as unknown as pg.Pool;const started=Date.now(),result=await runRestoreChecker({pool:delayed,storage,manifest:await manifest(),runningApplicationRelease:"release-59",manifestReference:"test",overallTimeoutMs:100});assert.ok(Date.now()-started<225);assert.equal(result.overallStatus,"FAIL");assert.ok(result.findings.some(f=>f.code==="VERIFICATION_DEADLINE_EXCEEDED"));await new Promise(resolve=>setTimeout(resolve,200));assert.equal(released,1)});
test("a delayed final PostgreSQL operation is database-bounded and cannot false-pass",async()=>{await hydrateStorage();const started=Date.now(),result=await runRestoreChecker({pool:poolWithDelayedQuery(/security_status='SCANNING'/,1),storage,manifest:await manifest(),runningApplicationRelease:"release-59",manifestReference:"test",overallTimeoutMs:500});assert.ok(Date.now()-started<900);assert.equal(result.overallStatus,"FAIL");assert.ok(result.findings.some(f=>f.code==="VERIFICATION_DEADLINE_EXCEEDED"));assert.ok(!result.checks.some(check=>check.name==="external-payment-reality"))});
test.after(async()=>{await Promise.all([app.end(),admin.end()])});
