import assert from "node:assert/strict";
import {randomUUID} from "node:crypto";
import test from "node:test";
import pg from "pg";

const appUrl=process.env.DATABASE_URL,workerUrl=process.env.DOCUMENT_WORKER_DATABASE_URL,adminUrl=process.env.AIMS_INTEGRATION_ADMIN_DATABASE_URL;
if(!appUrl||!workerUrl||!adminUrl)throw new Error("isolated application, worker, and administrator database URLs are required");
const app=new pg.Pool({connectionString:appUrl}),worker=new pg.Pool({connectionString:workerUrl}),admin=new pg.Pool({connectionString:adminUrl});

type Claim={document_id:string;document_version:number;storage_backend_id:string;source_object_key:string;source_object_version:string;document_sha256:string;document_size_bytes:number;scan_attempt:number;claim_token:string};
async function fixture(){const base=(await app.query<{request_id:string;user_id:string}>("SELECT id request_id,created_by user_id FROM payment_requests LIMIT 1")).rows[0];const id=randomUUID(),key=`quarantine/p13-3-1/${id}`,version=`opaque-${randomUUID()}`,sha=randomUUID().replaceAll("-","").repeat(2);await app.query(`INSERT INTO payment_documents(id,payment_request_id,logical_document_id,original_filename,storage_object_key,mime_type,size_bytes,sha256,document_type,version,uploaded_by,storage_provider,declared_mime_type,detected_mime_type,security_status,storage_binding_state,storage_backend_id,storage_object_version)VALUES($1,$2,$3,'proof.pdf',$4,'application/pdf',4,$5,'INVOICE',1,$6,'LOCAL','application/pdf','application/pdf','QUARANTINED','VERSION_BOUND','proof-backend',$7)`,[id,base.request_id,randomUUID(),key,sha,base.user_id,version]);return{id,key,version,sha}}
async function claim():Promise<Claim>{const row=(await worker.query("SELECT * FROM claim_next_payment_document_scan('migration-061-proof',30,3,$1)",[randomUUID()])).rows[0];assert.ok(row);return row}
async function complete(c:Claim,overrides:Partial<Claim>={}){const x={...c,...overrides};return worker.query("SELECT complete_payment_document_scan($1,$2,$3,$4,$5,$6,$7,$8,$9,'CLEAN',NULL,0,'proof-scanner','proof-clean',NULL,$10,$11)",[x.document_id,x.document_version,x.storage_backend_id,x.source_object_key,x.source_object_version,x.document_sha256,x.document_size_bytes,x.scan_attempt,x.claim_token,`active/${x.document_id}`,`trusted-${x.document_id}`])}
async function finish(c:Claim,status:"REJECTED"|"SCAN_FAILED",disposition:string|null=null,retryDelay=0,failureCode:string|null=null){return worker.query("SELECT complete_payment_document_scan($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,'proof-scanner','proof-result',$13,NULL,NULL)",[c.document_id,c.document_version,c.storage_backend_id,c.source_object_key,c.source_object_version,c.document_sha256,c.document_size_bytes,c.scan_attempt,c.claim_token,status,disposition,retryDelay,failureCode])}
async function claimWith(maxAttempts:number,workerId="migration-061-recovery-proof"):Promise<Claim|undefined>{return(await worker.query("SELECT * FROM claim_next_payment_document_scan($1,30,$2,$3)",[workerId,maxAttempts,randomUUID()])).rows[0]}
async function advance(reason:string){return asRole("aims_migrator","SELECT * FROM advance_aims_recovery_generation($1,$2)",[reason,randomUUID()])}
async function reachAttempt(id:string,target:number,maxAttempts:number){let current:Claim|undefined;for(let attempt=1;attempt<=target;attempt+=1){current=await claimWith(maxAttempts);assert.equal(current?.document_id,id);assert.equal(current?.scan_attempt,attempt);if(attempt<target){await finish(current!,"SCAN_FAILED","RETRYABLE",1,"SCANNER_UNAVAILABLE");await admin.query("UPDATE payment_documents SET scan_next_attempt_at=clock_timestamp()-interval '1 second' WHERE id=$1",[id])}}return current!}
async function asRole(role:string,sql:string,values:unknown[]=[]){const client=await admin.connect();try{await client.query("BEGIN");await client.query(`SET LOCAL ROLE ${role}`);const result=await client.query(sql,values);await client.query("COMMIT");return result}catch(error){await client.query("ROLLBACK");throw error}finally{client.release()}}

test("schema 61 singleton records the exact latest migration",async()=>{const current=(await admin.query("SELECT version,migration_id FROM aims_schema_version WHERE singleton")).rows[0];assert.deepEqual(current,{version:61,migration_id:"061_p13_storage_object_version_binding"});assert.equal(Number((await admin.query("SELECT count(*) count FROM aims_schema_version WHERE singleton AND version=61 AND migration_id='061_p13_storage_object_version_binding'")).rows[0].count),1)});

test("partial binding and runtime source/trust rebinding are denied",async()=>{const base=(await app.query("SELECT id request_id,created_by user_id FROM payment_requests LIMIT 1")).rows[0];await assert.rejects(()=>app.query(`INSERT INTO payment_documents(id,payment_request_id,logical_document_id,original_filename,storage_object_key,mime_type,size_bytes,sha256,version,uploaded_by,storage_provider,declared_mime_type,detected_mime_type,security_status,storage_binding_state,storage_backend_id)VALUES($1,$2,$3,'partial.pdf',$4,'application/pdf',4,$5,1,$6,'LOCAL','application/pdf','application/pdf','QUARANTINED','VERSION_BOUND','proof-backend')`,[randomUUID(),base.request_id,randomUUID(),`quarantine/${randomUUID()}`,"b".repeat(64),base.user_id]),/constraint|violates/i);const f=await fixture();for(const [column,value] of [["storage_object_key","quarantine/rebound"],["storage_object_version","rebound"],["storage_backend_id","other"],["sha256","c".repeat(64)],["size_bytes",5],["version",2],["trusted_storage_object_key","active/forged"],["trusted_storage_object_version","forged"]] as const)await assert.rejects(()=>app.query(`UPDATE payment_documents SET ${column}=$2 WHERE id=$1`,[f.id,value]),/permission denied|immutable|write-once/i);await admin.query("UPDATE payment_documents SET removed_at=now() WHERE id=$1",[f.id])});

test("trusted completion compares the entire claim and trusted identity is write-once",async()=>{const f=await fixture(),c=await claim();assert.equal(c.document_id,f.id);for(const forged of [{storage_backend_id:"wrong"},{source_object_key:"wrong"},{source_object_version:"wrong"},{document_sha256:"d".repeat(64)},{document_size_bytes:c.document_size_bytes+1},{document_version:c.document_version+1}])await assert.rejects(()=>complete(c,forged),/physical identity mismatch/);await complete(c);const clean=(await app.query("SELECT security_status,trusted_storage_object_key,trusted_storage_object_version FROM payment_documents WHERE id=$1",[f.id])).rows[0];assert.equal(clean.security_status,"CLEAN");assert.ok(clean.trusted_storage_object_key);assert.ok(clean.trusted_storage_object_version);await assert.rejects(()=>complete(c),/stale/);for(const sql of ["UPDATE payment_documents SET trusted_storage_object_key=NULL WHERE id=$1","UPDATE payment_documents SET trusted_storage_object_version='changed' WHERE id=$1"])await assert.rejects(()=>asRole("aims_app",sql,[f.id]),/permission denied|write-once/i)});

test("NULL claim lease and maximum attempts are rejected before every mutation",async()=>{const f=await fixture(),snapshot=async()=>({row:(await app.query("SELECT security_status,scan_attempt,scan_claim_token,scan_claimed_by,scan_claimed_at,scan_lease_expires_at,scan_next_attempt_at,scan_claim_generation FROM payment_documents WHERE id=$1",[f.id])).rows[0],audit:Number((await app.query("SELECT count(*) count FROM audit_events WHERE safe_metadata->>'documentId'=$1",[f.id])).rows[0].count)}),before=await snapshot();for(const [lease,maximum] of [[null,3],[30,null],[null,null]] as const){await assert.rejects(()=>worker.query("SELECT * FROM claim_next_payment_document_scan('null-claim-proof',$1::integer,$2::integer,$3)",[lease,maximum,randomUUID()]),/invalid document worker claim parameters/);assert.deepEqual(await snapshot(),before)}const valid=await claim();assert.equal(valid.document_id,f.id);await worker.query("SELECT complete_payment_document_scan($1,$2,$3,$4,$5,$6,$7,$8,$9,'REJECTED',NULL,0,'proof-scanner','valid-claim',NULL,NULL,NULL)",[valid.document_id,valid.document_version,valid.storage_backend_id,valid.source_object_key,valid.source_object_version,valid.document_sha256,valid.document_size_bytes,valid.scan_attempt,valid.claim_token])});

test("recovery-fenced scans terminalize at the attempt ceiling without resurrection",async()=>{
 const atMax=await fixture(),oldClaim=await reachAttempt(atMax.id,3,3);await advance("MIGRATION_061_AT_MAX");
 const fenced=(await app.query("SELECT security_status,scan_attempt,scan_claim_token,scan_lease_expires_at,scan_claim_generation FROM payment_documents WHERE id=$1",[atMax.id])).rows[0];
 assert.deepEqual(fenced,{security_status:"SCANNING",scan_attempt:3,scan_claim_token:null,scan_lease_expires_at:null,scan_claim_generation:null});
 await assert.rejects(()=>complete(oldClaim),/stale/);
 const concurrent=await Promise.all([claimWith(3,"recovery-worker-a"),claimWith(3,"recovery-worker-b")]);assert.deepEqual(concurrent,[undefined,undefined]);
 const terminal=(await app.query("SELECT security_status,scan_attempt,scan_claim_token,scan_lease_expires_at,scan_failure_code,scan_failure_disposition FROM payment_documents WHERE id=$1",[atMax.id])).rows[0];
 assert.deepEqual(terminal,{security_status:"SCAN_FAILED",scan_attempt:3,scan_claim_token:null,scan_lease_expires_at:null,scan_failure_code:"MAX_ATTEMPTS_EXHAUSTED",scan_failure_disposition:"TERMINAL"});
 const evidence=await app.query("SELECT action,safe_metadata FROM audit_events WHERE safe_metadata->>'documentId'=$1 AND action='DOCUMENT_SCAN_FAILED_TERMINAL'",[atMax.id]);assert.equal(evidence.rowCount,1);assert.equal(evidence.rows[0].safe_metadata.exhaustionCause,"RECOVERY_FENCED");
 assert.equal(await claimWith(3),undefined);await assert.rejects(()=>complete(oldClaim),/stale/);

 const aboveMax=await fixture();await reachAttempt(aboveMax.id,4,5);await advance("MIGRATION_061_ABOVE_MAX");assert.equal(await claimWith(3),undefined);
 const above=(await app.query("SELECT security_status,scan_attempt,scan_failure_code,scan_failure_disposition FROM payment_documents WHERE id=$1",[aboveMax.id])).rows[0];assert.deepEqual(above,{security_status:"SCAN_FAILED",scan_attempt:4,scan_failure_code:"MAX_ATTEMPTS_EXHAUSTED",scan_failure_disposition:"TERMINAL"});

 const belowMax=await fixture();const belowOld=await reachAttempt(belowMax.id,2,3);await advance("MIGRATION_061_BELOW_MAX");await assert.rejects(()=>complete(belowOld),/stale/);const reclaimed=await claimWith(3);assert.equal(reclaimed?.document_id,belowMax.id);assert.equal(reclaimed?.scan_attempt,3);assert.equal((await app.query("SELECT count(*) count FROM audit_events WHERE safe_metadata->>'documentId'=$1 AND action='DOCUMENT_SCAN_FAILED_TERMINAL'",[belowMax.id])).rows[0].count,"0");await finish(reclaimed!,"REJECTED");
});

test("recovery fencing leaves completed and legacy document truth unchanged",async()=>{
 const clean=await fixture();await complete(await claim());const rejected=await fixture();await finish((await claimWith(3))!,"REJECTED");const failed=await fixture();await finish((await claimWith(3))!,"SCAN_FAILED","TERMINAL",0,"UNSUPPORTED_FILE_TYPE");
 const base=(await app.query("SELECT id request_id,created_by user_id FROM payment_requests LIMIT 1")).rows[0],legacy=randomUUID();await app.query(`INSERT INTO payment_documents(id,payment_request_id,logical_document_id,original_filename,storage_object_key,mime_type,size_bytes,sha256,version,uploaded_by,storage_provider,declared_mime_type,detected_mime_type,security_status)VALUES($1,$2,$3,'legacy.pdf',$4,'application/pdf',4,$5,1,$6,'LOCAL','application/pdf','application/pdf','QUARANTINED')`,[legacy,base.request_id,randomUUID(),`quarantine/${legacy}`,"f".repeat(64),base.user_id]);
 const ids=[clean.id,rejected.id,failed.id,legacy],before=(await app.query("SELECT id,security_status,storage_binding_state,scan_attempt,scan_failure_code,scan_failure_disposition,trusted_storage_object_key,trusted_storage_object_version FROM payment_documents WHERE id=ANY($1::uuid[]) ORDER BY id",[ids])).rows;await advance("MIGRATION_061_COMPLETED_TRUTH");const after=(await app.query("SELECT id,security_status,storage_binding_state,scan_attempt,scan_failure_code,scan_failure_disposition,trusted_storage_object_key,trusted_storage_object_version FROM payment_documents WHERE id=ANY($1::uuid[]) ORDER BY id",[ids])).rows;assert.deepEqual(after,before);
});

test("completion rejects every NULL claim identity and incomplete trusted identity without mutation",async()=>{const f=await fixture(),c=await claim();assert.equal(c.document_id,f.id);const values:unknown[]=[c.document_id,c.document_version,c.storage_backend_id,c.source_object_key,c.source_object_version,c.document_sha256,c.document_size_bytes,c.scan_attempt,c.claim_token,"CLEAN",null,0,"proof-scanner","proof-clean",null,`active/${c.document_id}`,`trusted-${c.document_id}`];for(const index of [0,1,2,3,4,5,6,7,8,9,11,15,16]){const attacked=[...values];attacked[index]=null;await assert.rejects(()=>worker.query("SELECT complete_payment_document_scan($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17)",attacked),/required|trusted object identity|invalid/i);const row=(await app.query("SELECT security_status,scan_claim_token FROM payment_documents WHERE id=$1",[f.id])).rows[0];assert.equal(row.security_status,"SCANNING");assert.equal(row.scan_claim_token,c.claim_token)}await complete(c)});

test("recovery generation fences completion and legacy rows remain unbound and unclaimable",async()=>{const f=await fixture(),c=await claim();assert.equal(c.document_id,f.id);await asRole("aims_migrator","SELECT advance_aims_recovery_generation('MIGRATION_061_TEST',$1)",[randomUUID()]);await assert.rejects(()=>complete(c),/stale/);const base=(await app.query("SELECT id request_id,created_by user_id FROM payment_requests LIMIT 1")).rows[0],legacy=randomUUID();await app.query(`INSERT INTO payment_documents(id,payment_request_id,logical_document_id,original_filename,storage_object_key,mime_type,size_bytes,sha256,version,uploaded_by,storage_provider,declared_mime_type,detected_mime_type,security_status)VALUES($1,$2,$3,'legacy.pdf',$4,'application/pdf',4,$5,1,$6,'LOCAL','application/pdf','application/pdf','QUARANTINED')`,[legacy,base.request_id,randomUUID(),`quarantine/${legacy}`,"e".repeat(64),base.user_id]);assert.equal((await app.query("SELECT storage_binding_state,storage_backend_id,storage_object_version FROM payment_documents WHERE id=$1",[legacy])).rows[0].storage_binding_state,"LEGACY_UNBOUND");const next=(await worker.query("SELECT * FROM claim_next_payment_document_scan('legacy-proof',30,3,$1)",[randomUUID()])).rows[0];assert.notEqual(next?.document_id,legacy)});

test("only the document worker executor can claim or complete",async()=>{for(const role of ["aims_app","aims_finance_executor","aims_payment_executor"]){const privileges=(await admin.query("SELECT has_function_privilege($1,'claim_next_payment_document_scan(text,integer,integer,uuid)','EXECUTE') claim,has_function_privilege($1,'complete_payment_document_scan(uuid,integer,text,text,text,text,bigint,integer,uuid,text,text,integer,text,text,text,text,text)','EXECUTE') complete",[role])).rows[0];assert.equal(privileges.claim,false,role);assert.equal(privileges.complete,false,role)}const acl=(await admin.query("SELECT COALESCE(bool_or(e.grantee=0),false) public_execute FROM pg_proc p CROSS JOIN LATERAL aclexplode(COALESCE(p.proacl,acldefault('f',p.proowner))) e WHERE p.proname IN('claim_next_payment_document_scan','complete_payment_document_scan') AND e.privilege_type='EXECUTE'")).rows[0];assert.equal(acl.public_execute,false);const workerPrivileges=(await admin.query("SELECT has_function_privilege('aims_document_worker_executor','claim_next_payment_document_scan(text,integer,integer,uuid)','EXECUTE') claim,has_function_privilege('aims_document_worker_executor','complete_payment_document_scan(uuid,integer,text,text,text,text,bigint,integer,uuid,text,text,integer,text,text,text,text,text)','EXECUTE') complete")).rows[0];assert.deepEqual(workerPrivileges,{claim:true,complete:true})});

test.after(async()=>{await Promise.all([app.end(),worker.end(),admin.end()])});
