/* eslint-disable @typescript-eslint/no-explicit-any */
import { randomUUID } from 'node:crypto';
import { ForbiddenException,Injectable,NotFoundException } from '@nestjs/common';
import type { PoolClient } from 'pg';
import { calculateBudget,decimalToMinor,FINANCE_CONTEXT_CALCULATION_VERSION,minorToDecimal,type FinanceContextException } from '../../domain/finance-context.js';
import type { Principal } from '../../domain/payment-request.js';
import { Postgres } from '../../infrastructure/database/postgres.js';
import { PaymentRequestService } from '../payment-requests/payment-request.service.js';

@Injectable()
export class FinanceContextService{
 constructor(private readonly db:Postgres,private readonly requests:PaymentRequestService){}
 async calculate(id:string,actor:Principal,correlationId:string,recalculate=false){
  if(!actor.roles.includes('FINANCE'))throw new ForbiddenException('Finance permission required');
  try{return await this.db.transaction(async client=>{
   await client.query('SET TRANSACTION ISOLATION LEVEL SERIALIZABLE');
   const request=await this.requests.lockRequest(client,id);
   const current=await client.query<any>('SELECT * FROM finance_context_snapshots WHERE payment_request_id=$1 AND is_current FOR UPDATE',[id]);
   if(current.rowCount&&current.rows[0].request_revision===request.rowVersion&&!recalculate)return present(current.rows[0],true);
   if(current.rowCount){await client.query("UPDATE finance_context_snapshots SET is_current=false,status='SUPERSEDED' WHERE id=$1",[current.rows[0].id]);await this.requests.audit(client,actor.id,'FINANCE_CONTEXT_SUPERSEDED',id,request.status,request.status,correlationId,{contextId:current.rows[0].id,requestRevision:current.rows[0].request_revision});}
   await this.requests.audit(client,actor.id,'FINANCE_CONTEXT_STARTED',id,request.status,request.status,correlationId,{requestRevision:request.rowVersion,calculationVersion:FINANCE_CONTEXT_CALCULATION_VERSION});
   const validation=await client.query<any>(`SELECT vr.id FROM validation_runs vr WHERE vr.payment_request_id=$1 AND vr.is_current AND vr.status='COMPLETED' AND vr.overall_result='PASS' AND vr.request_revision=$2`,[id,request.rowVersion]);
   const clarification=await client.query('SELECT 1 FROM validation_clarifications WHERE payment_request_id=$1 AND status=$2',[id,'OPEN']);
   if(!validation.rowCount||clarification.rowCount)return this.exception(client,request,actor,correlationId,'STALE_VALIDATION');
   let requestMinor:bigint;try{requestMinor=decimalToMinor(request.amount??'')}catch{return this.exception(client,request,actor,correlationId,'INVALID_REQUEST_AMOUNT',0n)}
   const periods=await client.query<any>(`SELECT * FROM fiscal_periods WHERE status='ACTIVE' AND $1::date BETWEEN starts_on AND ends_on`,[request.dueDate]);
   if(periods.rowCount!==1)return this.exception(client,request,actor,correlationId,periods.rowCount?'AMBIGUOUS_BUDGET_MAPPING':'MISSING_APPLICABLE_BUDGET',requestMinor);
   const candidates=await client.query<any>(`SELECT b.*,bv.id budget_version_id,bv.version,bv.original_amount_minor,bv.revised_amount_minor FROM budgets b JOIN budget_versions bv ON bv.budget_id=b.id AND bv.status='ACTIVE' WHERE b.fiscal_period_id=$1 AND b.department_id=$2 AND b.category=$3 AND b.status='ACTIVE'`,[periods.rows[0].id,request.departmentId,request.category]);
   if(candidates.rowCount===0){const inactive=await client.query('SELECT 1 FROM budgets WHERE fiscal_period_id=$1 AND department_id=$2 AND category=$3 AND status=$4',[periods.rows[0].id,request.departmentId,request.category,'INACTIVE']);return this.exception(client,request,actor,correlationId,inactive.rowCount?'INACTIVE_BUDGET':'MISSING_APPLICABLE_BUDGET',requestMinor)}
   const matching=candidates.rows.filter((row:any)=>row.currency===request.currency);
   if(!matching.length)return this.exception(client,request,actor,correlationId,'CURRENCY_CONTEXT_UNSUPPORTED',requestMinor);
   if(matching.length!==1)return this.exception(client,request,actor,correlationId,'AMBIGUOUS_BUDGET_MAPPING',requestMinor);
   const budget=matching[0];await client.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[budget.id]);
   const totals=await client.query<any>(`SELECT COALESCE((SELECT sum(amount_minor) FROM financial_ledger_entries WHERE budget_id=$1 AND entry_type='ACTUAL'),0)::bigint actual,COALESCE((SELECT sum(amount_minor) FROM budget_commitments WHERE budget_id=$1 AND status='ACTIVE'),0)::bigint committed,COALESCE((SELECT bool_or(currency<>$2) FROM financial_ledger_entries WHERE budget_id=$1),false) OR COALESCE((SELECT bool_or(currency<>$2) FROM budget_commitments WHERE budget_id=$1 AND status='ACTIVE'),false) currency_mismatch`,[budget.id,budget.currency]);
   if(totals.rows[0].currency_mismatch)return this.exception(client,request,actor,correlationId,'INCONSISTENT_BUDGET_DATA',requestMinor);
   const revised=BigInt(budget.revised_amount_minor),actual=BigInt(totals.rows[0].actual),committed=BigInt(totals.rows[0].committed);let calculation;try{calculation=calculateBudget(revised,actual,committed,requestMinor)}catch{return this.exception(client,request,actor,correlationId,'INCONSISTENT_BUDGET_DATA',requestMinor)}
   const history=await this.history(client,budget.id,periods.rows[0].starts_on);
   const version=await this.nextVersion(client,id);const snapshotId=randomUUID();
   const inserted=await client.query<any>(`INSERT INTO finance_context_snapshots(id,payment_request_id,request_revision,finance_context_version,status,fiscal_period_id,fiscal_year,budget_id,budget_version_id,budget_version,department_id,category,cost_centre,request_currency,budget_currency,original_amount_minor,revised_amount_minor,actual_amount_minor,committed_amount_minor,available_amount_minor,request_amount_minor,projected_available_amount_minor,category_original_amount_minor,category_revised_amount_minor,category_actual_amount_minor,category_committed_amount_minor,category_available_amount_minor,historical_summary,calculation_version,calculated_by) VALUES($1,$2,$3,$4,'COMPLETED',$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$15,$16,$17,$18,$19,$22,$23,$24) RETURNING *`,[snapshotId,id,request.rowVersion,version,periods.rows[0].id,periods.rows[0].fiscal_year,budget.id,budget.budget_version_id,budget.version,request.departmentId,request.category,budget.cost_centre,request.currency,budget.currency,budget.original_amount_minor,budget.revised_amount_minor,actual.toString(),committed.toString(),calculation.available.toString(),requestMinor.toString(),calculation.projectedAvailable.toString(),JSON.stringify(history),FINANCE_CONTEXT_CALCULATION_VERSION,actor.id]);
   await this.requests.audit(client,actor.id,'FINANCE_CONTEXT_COMPLETED',id,request.status,request.status,correlationId,{contextId:snapshotId,requestRevision:request.rowVersion,budgetVersionId:budget.budget_version_id,calculationVersion:FINANCE_CONTEXT_CALCULATION_VERSION});
   if(recalculate)await this.requests.audit(client,actor.id,'FINANCE_CONTEXT_RECALCULATED',id,request.status,request.status,correlationId,{contextId:snapshotId,requestRevision:request.rowVersion,calculationVersion:FINANCE_CONTEXT_CALCULATION_VERSION});
   return present(inserted.rows[0],true);
  });}catch(error){if(isPgConflict(error)){const current=await this.db.pool.query<any>('SELECT * FROM finance_context_snapshots WHERE payment_request_id=$1 AND is_current',[id]);if(current.rowCount)return present(current.rows[0],true)}throw error}
 }
 async get(id:string,actor:Principal,history:boolean){await this.requests.get(id,actor);const rows=await this.db.pool.query<any>(`SELECT * FROM finance_context_snapshots WHERE payment_request_id=$1 ${history?'':'AND is_current'} ORDER BY calculated_at DESC`,[id]);if(!history&&!rows.rowCount)throw new NotFoundException('Finance Context not found');const privileged=actor.roles.includes('FINANCE');return history?rows.rows.map(row=>present(row,privileged)):present(rows.rows[0],privileged)}
 private async exception(client:PoolClient,request:any,actor:Principal,correlationId:string,code:FinanceContextException,requestMinor=0n){const version=await this.nextVersion(client,request.id);const id=randomUUID();const row=await client.query<any>(`INSERT INTO finance_context_snapshots(id,payment_request_id,request_revision,finance_context_version,status,exception_code,department_id,category,request_currency,request_amount_minor,calculation_version,calculated_by) VALUES($1,$2,$3,$4,'EXCEPTION',$5,$6,$7,$8,$9,$10,$11) RETURNING *`,[id,request.id,request.rowVersion,version,code,request.departmentId,request.category,request.currency??'XXX',requestMinor.toString(),FINANCE_CONTEXT_CALCULATION_VERSION,actor.id]);await this.requests.audit(client,actor.id,'FINANCE_CONTEXT_FAILED',request.id,request.status,request.status,correlationId,{contextId:id,requestRevision:request.rowVersion,failureCode:code,calculationVersion:FINANCE_CONTEXT_CALCULATION_VERSION});return present(row.rows[0],true)}
 private async nextVersion(client:PoolClient,id:string){const result=await client.query<{version:number}>('SELECT COALESCE(max(finance_context_version),0)+1 version FROM finance_context_snapshots WHERE payment_request_id=$1',[id]);return result.rows[0].version}
 private async history(client:PoolClient,budgetId:string,startsOn:string|Date){const result=await client.query<any>(`SELECT COALESCE(sum(amount_minor) FILTER(WHERE posted_at>=date_trunc('month',now())),0)::bigint current_month,COALESCE(sum(amount_minor) FILTER(WHERE posted_at>=date_trunc('month',now())-interval '1 month' AND posted_at<date_trunc('month',now())),0)::bigint previous_month,COALESCE(sum(amount_minor) FILTER(WHERE posted_at>=date_trunc('month',now())-interval '3 month'),0)::bigint rolling3,COALESCE(sum(amount_minor) FILTER(WHERE posted_at>=date_trunc('month',now())-interval '6 month'),0)::bigint rolling6,COALESCE(sum(amount_minor) FILTER(WHERE posted_at >= $2),0)::bigint ytd,count(*)::int count FROM financial_ledger_entries WHERE budget_id=$1`,[budgetId,startsOn]);const r=result.rows[0];return {hasData:r.count>0,currentMonthActualMinor:String(r.current_month),previousMonthActualMinor:String(r.previous_month),rolling3MonthAverageMinor:(BigInt(r.rolling3)/3n).toString(),rolling6MonthAverageMinor:(BigInt(r.rolling6)/6n).toString(),yearToDateActualMinor:String(r.ytd)}}
}
function present(row:any,privileged:boolean){const money=(value:any)=>value===null||value===undefined?null:{minor:String(value),decimal:minorToDecimal(value)};const base={id:row.id,status:row.status,exceptionCode:row.exception_code,requestRevision:row.request_revision,financeContextVersion:row.finance_context_version,fiscalYear:row.fiscal_year,departmentId:row.department_id,category:row.category,costCentre:row.cost_centre,requestCurrency:row.request_currency,budgetCurrency:row.budget_currency,originalBudget:money(row.original_amount_minor),revisedBudget:money(row.revised_amount_minor),actual:money(row.actual_amount_minor),committed:money(row.committed_amount_minor),available:money(row.available_amount_minor),requestAmount:money(row.request_amount_minor),projectedAvailable:money(row.projected_available_amount_minor),categoryContext:{original:money(row.category_original_amount_minor),revised:money(row.category_revised_amount_minor),actual:money(row.category_actual_amount_minor),committed:money(row.category_committed_amount_minor),available:money(row.category_available_amount_minor)},historicalSummary:row.historical_summary,calculationVersion:row.calculation_version,calculatedAt:row.calculated_at,readyForFinancialRiskAnalysis:row.status==='COMPLETED'};return privileged?{...base,budgetId:row.budget_id,budgetVersionId:row.budget_version_id,budgetVersion:row.budget_version}:base}
function isPgConflict(error:unknown){return typeof error==='object'&&error!==null&&'code' in error&&((error as {code?:string}).code==='40001'||(error as {code?:string}).code==='23505')}
